#packmode normal

//crystaltine
mods.extendedcrafting.TableCrafting.remove(<extendedcrafting:material:24>);

mods.extendedcrafting.TableCrafting.addShaped(3, <extendedcrafting:material:24>, [[<avaritia:resource:0>,<ore:gemLapis>,<ore:gemLapis>,<ore:gemLapis>,<ore:gemLapis>,<ore:gemLapis>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:ingotCobalt>,<ore:ingotOsmium>,<appliedenergistics2:material:10>,<ore:ingotOsmium>,<ore:ingotCobalt>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:ingotCobalt>,<ore:ingotOsmium>,<appliedenergistics2:material:10>,<ore:ingotOsmium>,<ore:ingotCobalt>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:gemLapis>,<ore:gemLapis>,<ore:gemLapis>,<ore:gemLapis>,<ore:gemLapis>,<avaritia:resource:0>], [null,null,null,null,null,null,null], [null,null,null,null,null,null,null], [null,null,null,null,null,null,null]]);

//crystal matrix
mods.extendedcrafting.TableCrafting.addShaped(3, <avaritia:resource:1>, [[<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>,<ore:ingotFiery>,<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<ore:netherStar>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<ore:netherStar>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<avaritia:resource:0>], [<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>,<ore:ingotFiery>,<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>], [null,null,null,null,null,null,null], [null,null,null,null,null,null,null], [null,null,null,null,null,null,null]]);

//creative modifier
mods.extendedcrafting.TableCrafting.addShaped(3, <tconstruct:materials:50>, [[<ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotAlumite>, <ore:ingotAlumite>, <ore:ingotCrystaltine>, <ore:ingotAlumite>, <ore:ingotAlumite>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotAlumite>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotAlumite>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotCrystaltine>, <ore:ingotAlumite>, <ore:ingotAlumite>, <ore:ingotAlumite>, <ore:ingotCrystaltine>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>]]);

//creative cobble generator
mods.extendedcrafting.TableCrafting.addShaped(3, <compacter:cobbler>, [[<tp:emerald_cobblegen_block>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <tp:emerald_cobblegen_block>], [<contenttweaker:neutral_steel_8>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <contenttweaker:neutral_steel_8>], [<contenttweaker:neutral_steel_8>, <ore:ingotCrystaltine>, <ore:compressed3xCobblestone>, <ore:compressed3xCobblestone>, <ore:compressed3xCobblestone>, <ore:ingotCrystaltine>, <contenttweaker:neutral_steel_8>], [<contenttweaker:neutral_steel_8>, <ore:ingotCrystaltine>, <ore:compressed3xCobblestone>, <ore:compressed3xCobblestone>, <ore:compressed3xCobblestone>, <ore:ingotCrystaltine>, <contenttweaker:neutral_steel_8>], [<contenttweaker:neutral_steel_8>, <ore:ingotCrystaltine>, <ore:compressed3xCobblestone>, <ore:compressed3xCobblestone>, <ore:compressed3xCobblestone>, <ore:ingotCrystaltine>, <contenttweaker:neutral_steel_8>], [<contenttweaker:neutral_steel_8>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <contenttweaker:neutral_steel_8>], [<tp:emerald_cobblegen_block>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <contenttweaker:neutral_steel_8>, <tp:emerald_cobblegen_block>]]);

//wand of animation
mods.extendedcrafting.TableCrafting.addShaped(3, <erebus:wand_of_animation>, [[null, null, null, null, null, <contenttweaker:neutral_steel_7>, <contenttweaker:neutral_steel_7>], [null, null, null, null, <contenttweaker:neutral_steel_7>, <erebus:materials:64>, <contenttweaker:neutral_steel_7>], [null, null, null, <contenttweaker:neutral_steel_7>, <contenttweaker:neutral_steel_7>, <contenttweaker:neutral_steel_7>, null], [null, null, null, <contenttweaker:neutral_steel_7>, <contenttweaker:neutral_steel_7>, null, null], [null, null, <ore:plateSteel>, null, null, null, null], [null, <ore:plateSteel>, null, null, null, null, null], [<contenttweaker:neutral_steel_7>, null, null, null, null, null, null]]);