#Noise added to map to make it look less plastic
#Range: 0.0 ~ 0.5
noise = 0.05
#Enables minimap to show up in corner
#Allowed Values: DISABLED, BOTTOM_LEFT, LEFT, TOP_LEFT, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
minimap = "DISABLED"
#Scale of minimap
#Range: 0.25 ~ 4.0
minimap_scale = 0.25
#Minimap will not rotate
minimap_locked_north = false
#Show waypoints on minimap
minimap_waypoints = false
#Show entities on minimap
minimap_entities = false
#Show entity heads on minimap
minimap_entity_heads = false
#Show player heads on minimap
minimap_player_heads = false
#Entities in minimap will be larger
minimap_large_entities = false
#Show XYZ under minimap
minimap_xyz = false
#Show biome under minimap
minimap_biome = false
#Blurs minimap
minimap_blur = false
#Adds NWSE compass inside minimap
minimap_compass = false

