#priority 4
#packmode titan
//removed
recipes.remove(<industrialforegoing:mob_duplicator>);
recipes.remove(<overloaded:fluid_core>);
recipes.remove(<overloaded:item_core>);
recipes.remove(<overloaded:energy_core>);
recipes.remove(<projectex:personal_link>);
recipes.remove(<mekanism:machineblock:8>);
recipes.remove(<enderio:item_power_conduit:*>);
recipes.remove(<enderio:item_endergy_conduit:*>);
recipes.remove(<enderio:item_liquid_conduit:2>);
recipes.remove(<enderio:item_liquid_conduit:1>);
recipes.remove(<extendedcrafting:interface>);
recipes.remove(<extendedcrafting:compressor>);
mods.extrautils2.Resonator.remove(<extrautils2:ingredients:3>);
recipes.remove(<botania:terraplate>);
recipes.remove(<minecraft:piston>);
recipes.remove(<minecraft:furnace>);
recipes.remove(<mob_grinding_utils:fan>);
recipes.remove(<botania:spark>);
recipes.remove(<draconicevolution:draconic_core>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<mekanism:machineblock:0>);
recipes.remove(<yabba:upgrade_star_tier>);
recipes.remove(<yabba:upgrade_diamond_tier>);
recipes.remove(<yabba:upgrade_gold_tier>);
recipes.remove(<storagedrawers:upgrade_storage:4>);
recipes.remove(<storagedrawers:upgrade_storage:3>);
recipes.remove(<storagedrawers:upgrade_storage:2>);
recipes.remove(<storagedrawers:upgrade_storage:1>);
recipes.remove(<thermalfoundation:material:293>);
recipes.remove(<thermalfoundation:material:294>);
recipes.remove(<thermalfoundation:material:295>);
recipes.remove(<redstonearsenal:material:96>);
recipes.remove(<thermalfoundation:material:258>);
recipes.remove(<thermalfoundation:material:260>);
recipes.remove(<thermalfoundation:material:261>);
recipes.remove(<thermalfoundation:material:262>);
recipes.remove(<thermalfoundation:material:263>);
recipes.remove(<thermalfoundation:material:26>);
recipes.remove(<thermalfoundation:material:27>);
recipes.remove(<thermalfoundation:material:256>);
recipes.remove(<thermalfoundation:material:292>);
recipes.remove(<thermalfoundation:material:291>);
recipes.remove(<thermalfoundation:material:290>);
recipes.remove(<thermalfoundation:material:289>);
recipes.remove(<thermalfoundation:material:288>);
recipes.remove(<thermalfoundation:material:264>);
recipes.remove(<equivalentintegrations:transmutation_generator>);
recipes.remove(<equivalentintegrations:transmutation_chamber>);
recipes.remove(<mekanism:tierinstaller:0>);
recipes.remove(<mekanism:tierinstaller:3>);
recipes.remove(<mekanism:tierinstaller:2>);
recipes.remove(<mekanism:tierinstaller:1>);
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 8}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 7}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 6}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 5}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 4}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 3}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 2}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 1}));
recipes.remove(<mekanism:machineblock:7>.withTag({recipeType: 0}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 8}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 7}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 6}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 5}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 4}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 3}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 2}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 1}));
recipes.remove(<mekanism:machineblock:6>.withTag({recipeType: 0}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 8}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 7}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 6}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 5}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 4}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 3}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 2}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 1}));
recipes.remove(<mekanism:machineblock:5>.withTag({recipeType: 0}));
recipes.remove(<mysticalagriculture:vibrant_alloy_seeds>);
recipes.remove(<mysticalagriculture:electrotine_seeds>);
recipes.remove(<mysticalagriculture:steeleaf_seeds>);
recipes.remove(<mysticalagriculture:ironwood_seeds>);
recipes.remove(<mysticalagriculture:coralium_seeds>);
recipes.remove(<mysticalagriculture:black_quartz_seeds>);
recipes.remove(<mysticalagriculture:aquamarine_seeds>);
recipes.remove(<mysticalagriculture:ender_biotite_seeds>);
recipes.remove(<mysticalagriculture:sky_stone_seeds>);
recipes.remove(<mysticalagriculture:certus_quartz_seeds>);
recipes.remove(<mysticalagriculture:manasteel_seeds>);
recipes.remove(<mysticalagriculture:conductive_iron_seeds>);
recipes.remove(<mysticalagriculture:redstone_alloy_seeds>);
recipes.remove(<mysticalagriculture:electrical_steel_seeds>);
recipes.remove(<mysticalagriculture:ardite_seeds>);
recipes.remove(<mysticalagriculture:knightslime_seeds>);
recipes.remove(<mysticalagriculture:basalz_seeds>);
recipes.remove(<mysticalagriculture:blitz_seeds>);
recipes.remove(<mysticalagriculture:blizz_seeds>);
recipes.remove(<mysticalagriculture:spider_seeds>);
recipes.remove(<mysticalagriculture:rabbit_seeds>);
recipes.remove(<mysticalagriculture:guardian_seeds>);
recipes.remove(<mysticalagriculture:saltpeter_seeds>);
recipes.remove(<mysticalagriculture:tin_seeds>);
recipes.remove(<mysticalagriculture:bronze_seeds>);
recipes.remove(<mysticalagriculture:silver_seeds>);
recipes.remove(<mysticalagriculture:lead_seeds>);
recipes.remove(<mysticalagriculture:graphite_seeds>);
recipes.remove(<mysticalagriculture:creeper_seeds>);
recipes.remove(<mysticalagriculture:skeleton_seeds>);
recipes.remove(<mysticalagriculture:obsidian_seeds>);
recipes.remove(<mysticalagriculture:redstone_seeds>);
recipes.remove(<mysticalagriculture:glowstone_seeds>);
recipes.remove(<mysticalagriculture:nether_quartz_seeds>);
recipes.remove(<mysticalagriculture:iron_seeds>);
recipes.remove(<mysticalagriculture:ghast_seeds>);
recipes.remove(<mysticalagriculture:blaze_seeds>);
recipes.remove(<mysticalagriculture:experience_seeds>);
recipes.remove(<mysticalagriculture:end_seeds>);
recipes.remove(<mysticalagriculture:lapis_lazuli_seeds>);
recipes.remove(<mysticalagriculture:gold_seeds>);
recipes.remove(<mysticalagriculture:enderman_seeds>);
recipes.remove(<mysticalagriculture:steel_seeds>);
recipes.remove(<mysticalagriculture:nickel_seeds>);
recipes.remove(<mysticalagriculture:constantan_seeds>);
recipes.remove(<mysticalagriculture:electrum_seeds>);
recipes.remove(<mysticalagriculture:invar_seeds>);
recipes.remove(<mysticalagriculture:mithril_seeds>);
recipes.remove(<mysticalagriculture:ruby_seeds>);
recipes.remove(<mysticalagriculture:sapphire_seeds>);
recipes.remove(<mysticalagriculture:peridot_seeds>);
recipes.remove(<mysticalagriculture:signalum_seeds>);
recipes.remove(<mysticalagriculture:lumium_seeds>);
recipes.remove(<mysticalagriculture:fluxed_electrum_seeds>);
recipes.remove(<mysticalagriculture:hop_graphite_seeds>);
recipes.remove(<mysticalagriculture:cobalt_seeds>);
recipes.remove(<mysticalagriculture:soularium_seeds>);
recipes.remove(<mysticalagriculture:dark_steel_seeds>);
recipes.remove(<mysticalagriculture:pulsating_iron_seeds>);
recipes.remove(<mysticalagriculture:energetic_alloy_seeds>);
recipes.remove(<mysticalagriculture:elementium_seeds>);
recipes.remove(<mysticalagriculture:dawnstone_seeds>);
recipes.remove(<mysticalagriculture:osmium_seeds>);
recipes.remove(<mysticalagriculture:glowstone_ingot_seeds>);
recipes.remove(<mysticalagriculture:knightmetal_seeds>);
recipes.remove(<mysticalagriculture:fiery_ingot_seeds>);
recipes.remove(<mysticalagriculture:meteoric_iron_seeds>);
recipes.remove(<mysticalagriculture:abyssalnite_seeds>);
recipes.remove(<mysticalagriculture:thorium_seeds>);
recipes.remove(<mysticalagriculture:boron_seeds>);
recipes.remove(<mysticalagriculture:lithium_seeds>);
recipes.remove(<mysticalagriculture:magnesium_seeds>);
recipes.remove(<mysticalagriculture:starmetal_seeds>);
recipes.remove(<mysticalagriculture:jade_seeds>);
recipes.remove(<mysticalagriculture:compressed_iron_seeds>);
recipes.remove(<mysticalagriculture:fluix_seeds>);
recipes.remove(<mysticalagriculture:diamond_seeds>);
recipes.remove(<mysticalagriculture:emerald_seeds>);
recipes.remove(<mysticalagriculture:wither_skeleton_seeds>);
recipes.remove(<mysticalagriculture:titanium_seeds>);
recipes.remove(<mysticalagriculture:uranium_seeds>);
recipes.remove(<mysticalagriculture:platinum_seeds>);
recipes.remove(<mysticalagriculture:draconium_seeds>);
recipes.remove(<mysticalagriculture:manyullyn_seeds>);
recipes.remove(<mysticalagradditions:neutronium_seeds>);
recipes.remove(<mysticalagriculture:end_steel_seeds>);
recipes.remove(<mysticalagriculture:terrasteel_seeds>);
recipes.remove(<mysticalagriculture:refined_obsidian_seeds>);
recipes.remove(<mysticalagriculture:desh_seeds>);
recipes.remove(<mysticalagriculture:dreadium_seeds>);
recipes.remove(<mysticalagriculture:rock_crystal_seeds>);
recipes.remove(<mysticalagriculture:yellorium_seeds>);
recipes.remove(<mysticalagriculture:enderium_seeds>);
recipes.remove(<mysticalagriculture:iridium_seeds>);
recipes.remove(<mysticalagradditions:awakened_draconium_seeds>);
recipes.remove(<mysticalagradditions:dragon_egg_seeds>);
recipes.remove(<mysticalagradditions:nether_star_seeds>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<quantumstorage:quantum_tank>);
recipes.remove(<quantumstorage:quantum_storage_unit>);
recipes.remove(<thermalsolars:blocktitaniumblock>);

//removed shaped and shapeless
recipes.removeShaped(<danknull:dank_null_5>, [[null, <danknull:dank_null_panel_5>, null],[<danknull:dank_null_panel_5>, <danknull:dank_null_panel_5>, <danknull:dank_null_panel_5>], [null, <danknull:dank_null_panel_5>, null]]);
recipes.removeShaped(<danknull:dank_null_4>, [[null, <danknull:dank_null_panel_4>, null],[<danknull:dank_null_panel_4>, <danknull:dank_null_panel_4>, <danknull:dank_null_panel_4>], [null, <danknull:dank_null_panel_4>, null]]);
recipes.removeShaped(<danknull:dank_null_3>, [[null, <danknull:dank_null_panel_3>, null],[<danknull:dank_null_panel_3>, <danknull:dank_null_panel_3>, <danknull:dank_null_panel_3>], [null, <danknull:dank_null_panel_3>, null]]);
recipes.removeShaped(<danknull:dank_null_2>, [[null, <danknull:dank_null_panel_2>, null],[<danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>, <danknull:dank_null_panel_2>], [null, <danknull:dank_null_panel_2>, null]]);
recipes.removeShaped(<danknull:dank_null_1>, [[null, <danknull:dank_null_panel_1>, null],[<danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>, <danknull:dank_null_panel_1>], [null, <danknull:dank_null_panel_1>, null]]);
recipes.removeShapeless(<minecraft:planks:1> * 4, [ <harvestcraft:pammaple>]);
recipes.removeShapeless(<minecraft:planks> * 64, [<twilightforest:giant_log>]);
recipes.removeShaped(<minecraft:planks:1> * 4, [[<twilightforest:twilight_log:3>]]);
recipes.removeShaped(<minecraft:planks:2> * 4, [[<twilightforest:twilight_log:2>]]);
recipes.removeShaped(<minecraft:planks:1> * 4, [[<twilightforest:twilight_log:1>]]);
recipes.removeShaped(<minecraft:planks> * 4, [[<twilightforest:twilight_log>]]);
recipes.removeShapeless(<randomthings:spectreplank> * 4, [<randomthings:spectrelog>]);
recipes.removeShapeless(<minecraft:planks:3> * 4, [<harvestcraft:pampaperbark>]);
recipes.removeShapeless(<minecraft:planks:3> * 4, [<harvestcraft:pamcinnamon>]);
recipes.removeShaped(<natura:nether_planks:1> * 4, [[<natura:nether_logs2:15>]]);
recipes.removeShaped(<natura:nether_planks:1> * 4, [[<natura:nether_logs2>]]);
recipes.removeShaped(<natura:nether_planks:3> * 4, [[<natura:nether_logs:2>]]);
recipes.removeShaped(<natura:nether_planks:2> * 4, [[<natura:nether_logs:1>]]);
recipes.removeShaped(<natura:nether_planks> * 4, [[<natura:nether_logs>]]);
recipes.removeShaped(<natura:overworld_planks:8> * 4, [[<natura:redwood_logs:1>]]);
recipes.removeShaped(<natura:overworld_planks:7> * 4, [[<natura:overworld_logs2:3>]]);
recipes.removeShaped(<natura:overworld_planks:6> * 4, [[<natura:overworld_logs2:2>]]);
recipes.removeShaped(<natura:overworld_planks:5> * 4, [[<natura:overworld_logs2:1>]]);
recipes.removeShaped(<natura:overworld_planks:4> * 4, [[<natura:overworld_logs2>]]);
recipes.removeShaped(<natura:overworld_planks:3> * 4, [[<natura:overworld_logs:3>]]);
recipes.removeShaped(<natura:overworld_planks:2> * 4, [[<natura:overworld_logs:2>]]);
recipes.removeShaped(<natura:overworld_planks:1> * 4, [[<natura:overworld_logs:1>]]);
recipes.removeShaped(<natura:overworld_planks> * 4, [[<natura:overworld_logs>]]);
recipes.removeShapeless(<extrautils2:ironwood_planks:1> * 4, [<extrautils2:ironwood_log:1>]);
recipes.removeShapeless(<extrautils2:ironwood_planks> * 4, [<extrautils2:ironwood_log>]);
recipes.removeShapeless(<erebus:planks:11> * 4, [<erebus:log_scorched>]);
recipes.removeShapeless(<erebus:planks:10> * 4, [<erebus:log_marshwood>]);
recipes.removeShapeless(<erebus:planks:9> * 4, [<erebus:log_rotten>]);
recipes.removeShapeless(<erebus:planks:6> * 4, [<erebus:log_balsam>]);
recipes.removeShapeless(<erebus:planks:5> * 4, [<erebus:log_cypress>]);
recipes.removeShapeless(<erebus:planks:4> * 4, [<erebus:log_asper>]);
recipes.removeShapeless(<erebus:planks:3> * 4, [<erebus:log_mossbark>]);
recipes.removeShapeless(<erebus:planks:2> * 4, [<erebus:log_mahogany>]);
recipes.removeShapeless(<erebus:planks:1> * 4, [<erebus:log_eucalyptus>]);
recipes.removeShapeless(<erebus:planks> * 4, [<erebus:log_baobab>]);
recipes.removeShaped(<abyssalcraft:dreadplanks> * 4, [[<abyssalcraft:dreadlog>]]);
recipes.removeShaped(<abyssalcraft:dltplank> * 4, [[<abyssalcraft:dltlog>]]);
recipes.removeShaped(<minecraft:planks:5> * 4, [[<minecraft:log2:1>]]);
recipes.removeShaped(<minecraft:planks:4> * 4, [[<minecraft:log2>]]);
recipes.removeShaped(<minecraft:planks:3> * 4, [[<minecraft:log:3>]]);
recipes.removeShaped(<minecraft:planks:2> * 4, [[<minecraft:log:2>]]);
recipes.removeShaped(<minecraft:planks:1> * 4, [[<minecraft:log:1>]]);
recipes.removeShaped(<minecraft:planks> * 4, [[<minecraft:log>]]);

//added
recipes.addShapeless(<avaritia:resource:1> * 9, [<ore:blockCrystalMatrix>]);
recipes.addShapeless(<thermalsolars:blocktitaniumblock>, [<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>,<ore:ingotTitanium>]);
recipes.addShapeless(<projectred-exploration:stone:11>, [<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>,<ore:dustElectrotine>]);
recipes.addShapeless(<minecraft:diamond> * 9, [<ore:blockDiamond>]);
recipes.addShaped(<quantumstorage:quantum_storage_unit>, [[<thermalfoundation:glass_alloy>, <appliedenergistics2:material:47>, <thermalfoundation:glass_alloy>],[<appliedenergistics2:material:38>, <quantumstorage:chest_diamond>, <appliedenergistics2:material:38>], [<extraplanets:tier5_items:12>, <extraplanets:tier5_items:12>, <extraplanets:tier5_items:12>]]);
recipes.addShaped(<quantumstorage:quantum_tank>, [[<thermalfoundation:glass_alloy>, <appliedenergistics2:material:47>, <thermalfoundation:glass_alloy>],[<appliedenergistics2:material:57>, <extracells:certustank>, <appliedenergistics2:material:57>], [<extraplanets:tier5_items:12>, <extraplanets:tier5_items:12>, <extraplanets:tier5_items:12>]]);
recipes.addShaped(<mekanism:basicblock:8>, [[<ore:ingotSteel>, <ore:plasticGray>, <ore:ingotSteel>],[<ore:plasticGray>, <thermalexpansion:frame:0>, <ore:plasticGray>], [<ore:ingotSteel>, <ore:plasticGray>, <ore:ingotSteel>]]);
recipes.addShaped(<mysticalagradditions:insanium>, [[null, <ore:essenceSupremium>, null],[<ore:essenceSupremium>, <mysticalagriculture:infusion_crystal:*>, <ore:essenceSupremium>], [null, <ore:essenceSupremium>, null]]);
recipes.addShaped(<mysticalagriculture:crafting:4>, [[null, <ore:essenceSuperium>, null],[<ore:essenceSuperium>, <mysticalagriculture:infusion_crystal:*>, <ore:essenceSuperium>], [null, <ore:essenceSuperium>, null]]);
recipes.addShaped(<mysticalagriculture:crafting:3>, [[null, <ore:essenceIntermedium>, null],[<ore:essenceIntermedium>, <mysticalagriculture:infusion_crystal:*>, <ore:essenceIntermedium>], [null, <ore:essenceIntermedium>, null]]);
recipes.addShaped(<mysticalagriculture:crafting:2>, [[null, <ore:essencePrudentium>, null],[<ore:essencePrudentium>, <mysticalagriculture:infusion_crystal:*>, <ore:essencePrudentium>], [null, <ore:essencePrudentium>, null]]);
recipes.addShaped(<mysticalagriculture:crafting:1>, [[null, <ore:essenceInferium>, null],[<ore:essenceInferium>, <mysticalagriculture:infusion_crystal:*>, <ore:essenceInferium>], [null, <ore:essenceInferium>, null]]);
recipes.addShaped(<mysticalagriculture:master_infusion_crystal>, [[<lordcraft:shard_magic>, <ore:essenceInsanium>, <lordcraft:shard_magic>],[<ore:essenceInsanium>, <mysticalagriculture:infusion_crystal>.anyDamage(), <ore:essenceInsanium>], [<lordcraft:shard_magic>, <ore:essenceInsanium>, <lordcraft:shard_magic>]]);
recipes.addShaped(<mysticalagriculture:infusion_crystal>, [[<ore:shardProsperity>, <ore:essenceInsanium>, <ore:shardProsperity>],[<ore:essenceInsanium>, <matc:supremiumcrystal>, <ore:essenceInsanium>], [<ore:shardProsperity>, <ore:essenceInsanium>, <ore:shardProsperity>]]);
recipes.addShaped(<enderio:item_liquid_conduit> * 8, [[<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>],[<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>], [<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit> * 8, [[<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>],[<ore:ingotCrudeSteel>, <ore:ingotCrudeSteel>, <ore:ingotCrudeSteel>], [<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:11> * 4, [[<ore:itemConduitBinder>, <ore:ingotStellarAlloy>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:10>, <enderio:item_endergy_conduit:10>, <enderio:item_endergy_conduit:10>], [<ore:itemConduitBinder>, <ore:ingotStellarAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:10> * 4, [[<ore:itemConduitBinder>, <ore:ingotMelodicAlloy>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:9>, <enderio:item_endergy_conduit:9>, <enderio:item_endergy_conduit:9>], [<ore:itemConduitBinder>, <ore:ingotMelodicAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:9> * 4, [[<ore:itemConduitBinder>, <ore:ingotCrystallinePinkSlime>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:8>, <enderio:item_endergy_conduit:8>, <enderio:item_endergy_conduit:8>], [<ore:itemConduitBinder>, <ore:ingotCrystallinePinkSlime>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:8> * 4, [[<ore:itemConduitBinder>, <ore:ingotCrystallineAlloy>, <ore:itemConduitBinder>],[<enderio:item_power_conduit:2>, <enderio:item_power_conduit:2>, <enderio:item_power_conduit:2>], [<ore:itemConduitBinder>, <ore:ingotCrystallineAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_power_conduit:2> * 4, [[<ore:itemConduitBinder>, <ore:ingotVibrantAlloy>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:7>, <enderio:item_endergy_conduit:7>, <enderio:item_endergy_conduit:7>], [<ore:itemConduitBinder>, <ore:ingotVibrantAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:7> * 4, [[<ore:itemConduitBinder>, <ore:ingotEnergeticSilver>, <ore:itemConduitBinder>],[<enderio:item_power_conduit:1>, <enderio:item_power_conduit:1>, <enderio:item_power_conduit:1>], [<ore:itemConduitBinder>, <ore:ingotEnergeticSilver>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_power_conduit:1> * 4, [[<ore:itemConduitBinder>, <ore:ingotEnergeticAlloy>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:6>, <enderio:item_endergy_conduit:6>, <enderio:item_endergy_conduit:6>], [<ore:itemConduitBinder>, <ore:ingotEnergeticAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:6> * 4, [[<ore:itemConduitBinder>, <ore:ingotElectrum>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:5>, <enderio:item_endergy_conduit:5>, <enderio:item_endergy_conduit:5>], [<ore:itemConduitBinder>, <ore:ingotElectrum>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:5> * 4, [[<ore:itemConduitBinder>, <ore:ingotSilver>, <ore:itemConduitBinder>],[<enderio:item_power_conduit>, <enderio:item_power_conduit>, <enderio:item_power_conduit>], [<ore:itemConduitBinder>, <ore:ingotSilver>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_power_conduit> * 4, [[<ore:itemConduitBinder>, <ore:ingotConductiveIron>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:4>, <enderio:item_endergy_conduit:4>, <enderio:item_endergy_conduit:4>], [<ore:itemConduitBinder>, <ore:ingotConductiveIron>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:4> * 4, [[<ore:itemConduitBinder>, <ore:ingotCopper>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:3>, <enderio:item_endergy_conduit:3>, <enderio:item_endergy_conduit:3>], [<ore:itemConduitBinder>, <ore:ingotCopper>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:3> * 4, [[<ore:itemConduitBinder>, <ore:ingotGold>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:2>, <enderio:item_endergy_conduit:2>, <enderio:item_endergy_conduit:2>], [<ore:itemConduitBinder>, <ore:ingotGold>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:2> * 4, [[<ore:itemConduitBinder>, <ore:ingotAluminum>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit:1>, <enderio:item_endergy_conduit:1>, <enderio:item_endergy_conduit:1>], [<ore:itemConduitBinder>, <ore:ingotAluminum>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_endergy_conduit:1> * 4, [[<ore:itemConduitBinder>, <ore:ingotConstructionAlloy>, <ore:itemConduitBinder>],[<enderio:item_endergy_conduit>, <enderio:item_endergy_conduit>, <enderio:item_endergy_conduit>], [<ore:itemConduitBinder>, <ore:ingotConstructionAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_liquid_conduit:2> * 4, [[<ore:itemConduitBinder>, <ore:ingotVibrantAlloy>, <ore:itemConduitBinder>],[<enderio:item_liquid_conduit:1>, <enderio:item_liquid_conduit:1>, <enderio:item_liquid_conduit:1>], [<ore:itemConduitBinder>, <ore:ingotVibrantAlloy>, <ore:itemConduitBinder>]]);
recipes.addShaped(<enderio:item_liquid_conduit:1> * 4, [[<ore:itemConduitBinder>, <ore:blockGlassHardened>, <ore:itemConduitBinder>],[<enderio:item_liquid_conduit>, <enderio:item_liquid_conduit>, <enderio:item_liquid_conduit>], [<ore:itemConduitBinder>, <ore:blockGlassHardened>, <ore:itemConduitBinder>]]);
recipes.addShaped(<nuclearcraft:manufactory_idle>, [[<ore:ingotLead>, <ore:solenoidCopper>, <ore:ingotLead>],[<ore:solenoidCopper>, <bigreactors:reactorcasingcores>, <ore:solenoidCopper>], [<ore:ingotLead>, <ore:solenoidCopper>, <ore:ingotLead>]]);
recipes.addShaped(<extrautils2:teleporter:1>, [[<extrautils2:compressedcobblestone:7>, <actuallyadditions:block_crystal_empowered:3>, <extrautils2:compressedcobblestone:7>],[<actuallyadditions:block_crystal_empowered:3>, null, <actuallyadditions:block_crystal_empowered:3>], [<extrautils2:compressedcobblestone:7>, <actuallyadditions:block_crystal_empowered:3>, <extrautils2:compressedcobblestone:7>]]);
recipes.addShaped(<mekanism:tierinstaller:0>, [[<minecraft:redstone>, <ore:circuitBasic>, <minecraft:redstone>],[<ore:ingotMelodicAlloy>, <actuallyadditions:block_crystal:3>, <ore:ingotMelodicAlloy>], [<minecraft:redstone>, <ore:circuitBasic>, <minecraft:redstone>]]);
recipes.addShaped(<botania:terraplate>, [[<embers:ember_cluster>, <embers:ember_cluster>, <embers:ember_cluster>],[<botania:rune>, <botania:storage>, <botania:rune:8>], [<botania:rune:1>, <botania:rune:2>, <botania:rune:3>]]);
recipes.addShaped(<minecraft:piston>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>],[<ore:cobblestone>, <ore:blockIron>, <ore:cobblestone>], [<ore:cobblestone>, <ore:blockRedstone>, <ore:cobblestone>]]);
recipes.addShaped(<minecraft:furnace>, [[<ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>],[<ore:compressed1xCobblestone>, null, <ore:compressed1xCobblestone>], [<ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>]]);
recipes.addShaped(<mob_grinding_utils:fan>, [[<ore:slabStone>, <ore:ingotRedAlloy>, <ore:slabStone>],[<ore:ingotRedAlloy>, <ore:blockRedstone>, <ore:ingotRedAlloy>], [<ore:slabStone>, <ore:ingotRedAlloy>, <ore:slabStone>]]);
recipes.addShaped(<botania:spark>, [[null, <ore:petal>, null],[<minecraft:blaze_powder>, <embers:shard_ember>, <minecraft:blaze_powder>], [null, <ore:petal>, null]]);
recipes.addShaped(<draconicevolution:draconic_core>, [[<ore:ingotDraconium>, <ore:ingotGold>, <ore:ingotDraconium>],[<ore:ingotGold>, <ore:alloyUltimate>, <ore:ingotGold>], [<ore:ingotDraconium>, <ore:ingotGold>, <ore:ingotDraconium>]]);
recipes.addShaped(<appliedenergistics2:controller>, [[<ore:alloyUltimate>, <appliedenergistics2:material:24>, <ore:alloyUltimate>],[<bloodmagic:decorative_brick:2>, <ore:pcb>, <bloodmagic:decorative_brick:2>], [<ore:alloyUltimate>, <bloodmagic:decorative_brick:2>, <ore:alloyUltimate>]]);
recipes.addShaped(<mekanism:machineblock:0>, [[<minecraft:redstone>, <mekanism:controlcircuit>, <minecraft:redstone>],[<pneumaticcraft:plastic:15>, <mekanism:basicblock:8>, <pneumaticcraft:plastic:15>], [<minecraft:redstone>, <mekanism:controlcircuit>, <minecraft:redstone>]]);
recipes.addShapedMirrored(<yabba:upgrade_star_tier>, [[null, <ore:netherStar>, null],[null, <yabba:upgrade_diamond_tier>, null], [null, null, null]]);
recipes.addShaped(<yabba:upgrade_diamond_tier>, [[null, <ore:gemDiamond>, null],[<ore:gemDiamond>, <yabba:upgrade_gold_tier>, <ore:gemDiamond>], [null, <ore:gemDiamond>, null]]);
recipes.addShaped(<yabba:upgrade_gold_tier>, [[null, <ore:ingotGold>, null],[<ore:ingotGold>, <yabba:upgrade_iron_tier>, <ore:ingotGold>], [null, <ore:ingotGold>, null]]);
recipes.addShaped(<storagedrawers:upgrade_storage:4>, [[<ore:stickWood>, <ore:stickWood>, <ore:stickWood>],[<ore:gemEmerald>, <storagedrawers:upgrade_storage:3>, <ore:gemEmerald>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>]]);
recipes.addShaped(<storagedrawers:upgrade_storage:3>, [[<ore:stickWood>, <ore:stickWood>, <ore:stickWood>],[<ore:gemDiamond>, <storagedrawers:upgrade_storage:2>, <ore:gemDiamond>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>]]);
recipes.addShaped(<storagedrawers:upgrade_storage:2>, [[<ore:stickWood>, <ore:stickWood>, <ore:stickWood>],[<ore:ingotGold>, <storagedrawers:upgrade_storage:1>, <ore:ingotGold>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>]]);
recipes.addShaped(<storagedrawers:upgrade_storage:1>, [[<ore:stickWood>, <ore:stickWood>, <ore:stickWood>],[<ore:ingotIron>, <storagedrawers:upgrade_storage>, <ore:ingotIron>], [<ore:stickWood>, <ore:stickWood>, <ore:stickWood>]]);
recipes.addShaped(<equivalentintegrations:transmutation_generator>, [[<furnaceoverhaul:end_furnace>, <ore:plasticBlue>, <furnaceoverhaul:end_furnace>],[<ore:plasticBlue>, <projecte:item.pe_transmutation_tablet>, <ore:plasticBlue>], [<furnaceoverhaul:end_furnace>, <ore:plasticBlue>, <furnaceoverhaul:end_furnace>]]);
recipes.addShaped(<equivalentintegrations:transmutation_chamber>, [[<furnaceoverhaul:end_furnace>, <ore:gearIronCompressed>, <furnaceoverhaul:end_furnace>],[<ore:gearIronCompressed>, <projecte:item.pe_transmutation_tablet>, <ore:gearIronCompressed>], [<furnaceoverhaul:end_furnace>, <ore:gearIronCompressed>, <furnaceoverhaul:end_furnace>]]);
recipes.addShaped(<mekanism:machineblock:8>, [[<ore:ingotIron>, <astralsorcery:blockstarlightinfuser>, <ore:ingotIron>],[<bloodmagic:slate:2>, <ore:ingotOsmium>, <bloodmagic:slate:2>], [<ore:ingotIron>, <astralsorcery:blockstarlightinfuser>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:planks:1> * 2, [[<twilightforest:twilight_log:3>]]);
recipes.addShaped(<minecraft:planks:2> * 2, [[<twilightforest:twilight_log:2>]]);
recipes.addShaped(<minecraft:planks:1> * 2, [[<twilightforest:twilight_log:1>]]);
recipes.addShaped(<minecraft:planks> * 2, [[<twilightforest:twilight_log>]]);
recipes.addShaped(<randomthings:spectreplank> * 2, [[<randomthings:spectrelog>]]);
recipes.addShaped(<minecraft:planks:3> * 2, [[<harvestcraft:pampaperbark>]]);
recipes.addShaped(<minecraft:planks:1> * 2, [[<harvestcraft:pammaple>]]);
recipes.addShaped(<minecraft:planks:3> * 2, [[<harvestcraft:pamcinnamon>]]);
recipes.addShaped(<natura:nether_planks:1> * 2, [[<natura:nether_logs2:15>]]);
recipes.addShaped(<natura:nether_planks:1> * 2, [[<natura:nether_logs2>]]);
recipes.addShaped(<natura:nether_planks:3> * 2, [[<natura:nether_logs:2>]]);
recipes.addShaped(<natura:nether_planks:3> * 2, [[<natura:nether_logs:2>]]);
recipes.addShaped(<natura:nether_planks:2> * 2, [[<natura:nether_logs:1>]]);
recipes.addShaped(<natura:nether_planks> * 2, [[<natura:nether_logs>]]);
recipes.addShaped(<natura:overworld_planks:8> * 2, [[<natura:redwood_logs:1>]]);
recipes.addShaped(<natura:overworld_planks:7> * 2, [[<natura:overworld_logs2:3>]]);
recipes.addShaped(<natura:overworld_planks:6> * 2, [[<natura:overworld_logs2:2>]]);
recipes.addShaped(<natura:overworld_planks:6> * 2, [[<natura:overworld_logs2:1>]]);
recipes.addShaped(<natura:overworld_planks:5> * 2, [[<natura:overworld_logs2:1>]]);
recipes.addShaped(<natura:overworld_planks:4> * 2, [[<natura:overworld_logs2>]]);
recipes.addShaped(<natura:overworld_planks:3> * 2, [[<natura:overworld_logs:3>]]);
recipes.addShaped(<natura:overworld_planks:2> * 2, [[<natura:overworld_logs:2>]]);
recipes.addShaped(<natura:overworld_planks:1> * 2, [[<natura:overworld_logs:1>]]);
recipes.addShaped(<natura:overworld_planks> * 2, [[<natura:overworld_logs>]]);
recipes.addShaped(<extrautils2:ironwood_planks:1> * 2, [[<extrautils2:ironwood_log:1>]]);
recipes.addShaped(<extrautils2:ironwood_planks> * 2, [[<extrautils2:ironwood_log>]]);
recipes.addShaped(<erebus:planks:11> * 2, [[<erebus:log_scorched>]]);
recipes.addShaped(<erebus:planks:10> * 2, [[<erebus:log_marshwood>]]);
recipes.addShaped(<erebus:planks:9> * 2, [[<erebus:log_rotten>]]);
recipes.addShaped(<erebus:planks:6> * 2, [[<erebus:log_balsam>]]);
recipes.addShaped(<erebus:planks:5> * 2, [[<erebus:log_cypress>]]);
recipes.addShaped(<erebus:planks:4> * 2, [[<erebus:log_asper>]]);
recipes.addShaped(<erebus:planks:3> * 2, [[<erebus:log_mossbark>]]);
recipes.addShaped(<erebus:planks:2> * 2, [[<erebus:log_mahogany>]]);
recipes.addShaped(<erebus:planks:1> * 2, [[<erebus:log_eucalyptus>]]);
recipes.addShaped(<erebus:planks> * 2, [[<erebus:log_baobab>]]);
recipes.addShaped(<abyssalcraft:dreadplanks> * 2, [[<abyssalcraft:dreadlog>]]);
recipes.addShaped(<abyssalcraft:dltplank> * 2, [[<abyssalcraft:dltlog>]]);
recipes.addShaped(<minecraft:planks:5> * 2, [[<minecraft:log2:1>]]);
recipes.addShaped(<minecraft:planks:4> * 2, [[<minecraft:log2>]]);
recipes.addShaped(<minecraft:planks:3> * 2, [[<minecraft:log:3>]]);
recipes.addShaped(<minecraft:planks:2> * 2, [[<minecraft:log:2>]]);
recipes.addShaped(<minecraft:planks:1> * 2, [[<minecraft:log:1>]]);
recipes.addShaped(<minecraft:planks> * 2, [[<minecraft:log>]]);
recipes.addShaped(<minecraft:planks> * 2, [[<minecraft:log>]]);
recipes.addShaped(<minecraft:planks> * 2, [[<twilightforest:giant_log>]]);
recipes.addShaped(<rftools:machine_frame>, [[<ore:ingotExtreme>, <ore:ingotHardCarbon>, <ore:ingotExtreme>],[<ore:nuggetGold>, <thermalexpansion:frame:0>, <ore:nuggetGold>], [<ore:ingotExtreme>, <ore:ingotHardCarbon>, <ore:ingotExtreme>]]);
recipes.addShaped(<overloaded:fluid_core>, [[<mekanism:polyethene>, <appliedenergistics2:fluid_interface>, <mekanism:polyethene>],[<quantumstorage:quantum_tank>, <projectex:matter:11>, <quantumstorage:quantum_tank>], [<mekanism:polyethene>, <appliedenergistics2:fluid_interface>, <mekanism:polyethene>]]);
recipes.addShaped(<overloaded:energy_core>, [[<appliedenergistics2:material:23>, <ore:pcb>, <appliedenergistics2:material:23>],[<ore:pcb>, <projectex:matter:11>, <ore:pcb>], [<appliedenergistics2:material:23>, <ore:pcb>, <appliedenergistics2:material:23>]]);
recipes.addShaped(<overloaded:item_core>, [[<extracells:storage.component:2>, <storagedrawers:controller>, <extracells:storage.component:2>],[<quantumstorage:quantum_storage_unit>, <projectex:matter:11>, <quantumstorage:quantum_storage_unit>], [<extracells:storage.component:2>, <yabba:item_barrel_connector>, <extracells:storage.component:2>]]);
recipes.addShaped(<guideapi:bloodmagic-guide>, [[null, <tconstruct:edible:3>, null],[<tconstruct:edible:3>, <minecraft:book>, <tconstruct:edible:3>], [null, <tconstruct:edible:3>, null]]);

//replaced
recipes.replaceAllOccurences(<ore:ingotIron>, <ore:blockIron>, <tp:iron_cobblegen_block>);
recipes.replaceAllOccurences(<ore:gemDiamond>, <ore:blockDiamond>, <tp:diamond_cobblegen_block>);
recipes.replaceAllOccurences(<minecraft:blaze_rod>, <tconstruct:firewood:0>, <tp:blaze_cobblegen_block>);
recipes.replaceAllOccurences(<ore:gemEmerald>, <ore:blockEmerald>, <tp:emerald_cobblegen_block>);
recipes.replaceAllOccurences(<ore:blockGlass>, <extrautils2:ineffableglass:0>, <thermalexpansion:frame:0>);
recipes.replaceAllOccurences(<thermalexpansion:frame:0>, <thermalexpansion:cell:0>, <thermalexpansion:machine:9>);
recipes.replaceAllOccurences(<minecraft:furnace>, <embers:ember_activator>, <embers:boiler>);
recipes.replaceAllOccurences(<minecraft:dye:4>, <bloodmagic:decorative_brick:2>, <mekanism:teleportationcore>);
recipes.replaceAllOccurences(<minecraft:comparator>, <nuclearcraft:fusion_core>, <bigreactors:reactorcontroller>);
