#packmode kappa
//ITB
mods.extendedcrafting.TableCrafting.addShaped(0, <quantumflux:imaginarytime>, [[<tp:growth_upgrade_two>, <xreliquary:fertile_lilypad>, <quantumflux:craftingpiece:1>, <xreliquary:fertile_lilypad>, <tp:growth_upgrade_two>], [<quantumflux:craftingpiece>, <pneumaticcraft:transistor>, <pneumaticcraft:capacitor>, <pneumaticcraft:transistor>, <quantumflux:craftingpiece>], [<quantumflux:craftingpiece:1>, <pneumaticcraft:capacitor>, <quantumflux:quibitcluster:3>, <pneumaticcraft:capacitor>, <quantumflux:craftingpiece:1>], [<quantumflux:craftingpiece>, <pneumaticcraft:transistor>, <pneumaticcraft:capacitor>, <pneumaticcraft:transistor>, <quantumflux:craftingpiece>], [<tp:growth_upgrade_two>, <xreliquary:fertile_lilypad>, <quantumflux:craftingpiece:1>, <xreliquary:fertile_lilypad>, <tp:growth_upgrade_two>]]);

//7x7 table
recipes.remove(<extendedcrafting:table_elite>);

mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:table_elite>, [[<extendedcrafting:material:16>, <extendedcrafting:material:16>, <extendedcrafting:material:10>, <extendedcrafting:material:16>, <extendedcrafting:material:16>], [<extendedcrafting:material:16>, <ore:gemBlueDiamond>, <rftools:infused_diamond>, <ore:gemBlueDiamond>, <extendedcrafting:material:16>], [<extendedcrafting:table_advanced>, <rftools:infused_diamond>, <botania:storage:4>, <rftools:infused_diamond>, <extendedcrafting:table_advanced>], [<extendedcrafting:material:16>, <ore:gemBlueDiamond>, <rftools:infused_diamond>, <ore:gemBlueDiamond>, <extendedcrafting:material:16>], [<extendedcrafting:material:16>, <extendedcrafting:material:16>, <extendedcrafting:material:10>, <extendedcrafting:material:16>, <extendedcrafting:material:16>]]);

//automation interface
recipes.remove(<extendedcrafting:interface>);

mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:interface>, [[<ore:ingotBlackIron>, <ore:ingotBlackIron>, <extendedcrafting:material:10>, <ore:ingotBlackIron>, <ore:ingotBlackIron>], [<extendedcrafting:material:18>, <appliedenergistics2:crafting_accelerator>, <ore:ingotEnderEnhanced>, <appliedenergistics2:molecular_assembler>, <extendedcrafting:material:18>], [<extendedcrafting:material:18>, <ore:ingotEnderEnhanced>, <extendedcrafting:frame>, <ore:ingotEnderEnhanced>, <extendedcrafting:material:18>], [<extendedcrafting:material:18>, <appliedenergistics2:crafting_monitor>, <ore:ingotEnderEnhanced>, <appliedenergistics2:crafting_storage_64k>.noReturn(), <extendedcrafting:material:18>], [<ore:ingotBlackIron>, <extendedcrafting:material:2>, <extendedcrafting:material:2>, <extendedcrafting:material:2>, <ore:ingotBlackIron>]]);

//mob duplicator
mods.extendedcrafting.TableCrafting.addShaped(0, <industrialforegoing:mob_duplicator>, [[<ore:itemRubber>, <ore:gemRime>, <ore:cropNetherWart>, <ore:gemRime>, <ore:itemRubber>], [<ore:gemAmethyst>, <ore:dropofevil>, <ore:ingotCrystallineAlloy>, <ore:dropofevil>, <ore:gemAmethyst>], [<erebus:materials:60>, <thermalexpansion:frame>, <exnihilocreatio:item_material:5>, <teslacorelib:machine_case>, <erebus:materials:60>], [<ore:gemAmethyst>, <ore:crystalGold>, <ore:blockInfusedLavaCrystal>, <ore:crystalGold>, <ore:gemAmethyst>], [<ore:plasticLightGray>, <actuallyadditions:item_crystal_empowered:4>, <ore:ingotRedstoneAlloy>, <actuallyadditions:item_crystal_empowered:4>, <ore:plasticLightGray>]]);

//garden cloche
mods.extendedcrafting.TableCrafting.addShaped(0, <immersiveengineering:metal_device1:13>, [[<appliedenergistics2:quartz_vibrant_glass>, <appliedenergistics2:quartz_vibrant_glass>, <actuallyadditions:block_greenhouse_glass>, <appliedenergistics2:quartz_vibrant_glass>, <appliedenergistics2:quartz_vibrant_glass>], [<appliedenergistics2:quartz_vibrant_glass>, null, null, null, <appliedenergistics2:quartz_vibrant_glass>], [<actuallyadditions:block_greenhouse_glass>, null, <natura:colored_grass>, null, <actuallyadditions:block_greenhouse_glass>], [<ore:plateConstantan>, <ore:itemPulsatingCrystal>, <ore:electronTube>, <ore:itemPulsatingCrystal>, <ore:plateConstantan>], [<ore:plateConstantan>, <ore:scaffoldingTreatedWood>, <ore:scaffoldingTreatedWood>, <ore:scaffoldingTreatedWood>, <ore:plateConstantan>]]);
//seeds
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:diamond_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <agricraft:agri_seed>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "diamahlia_plant", agri_growth: 10 as byte}), <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDiamond>, <mysticalagriculture:crafting:21>, <ore:blockDiamond>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDiamond>, <ore:blockDiamond>, <ore:blockDiamond>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:emerald_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <agricraft:agri_seed>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "emeryllis_plant", agri_growth: 10 as byte}), <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockEmerald>, <ore:blockEmerald>, <ore:blockEmerald>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockEmerald>, <mysticalagriculture:crafting:21>, <ore:blockEmerald>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockEmerald>, <ore:blockEmerald>, <ore:blockEmerald>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:wither_skeleton_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <mysticalagriculture:skeleton_seeds>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <mysticalagriculture:chunk:20>, <mysticalagriculture:chunk:20>, <mysticalagriculture:chunk:20>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <mysticalagriculture:chunk:20>, <mysticalagriculture:crafting:21>, <mysticalagriculture:chunk:20>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <mysticalagriculture:chunk:20>, <mysticalagriculture:chunk:20>, <mysticalagriculture:chunk:20>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:titanium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockTitanium>, <mysticalagriculture:crafting:21>, <ore:blockTitanium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockTitanium>, <ore:blockTitanium>, <ore:blockTitanium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:uranium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockUranium>, <mysticalagriculture:crafting:21>, <ore:blockUranium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockUranium>, <ore:blockUranium>, <ore:blockUranium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:platinum_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <agricraft:agri_seed>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "resource:platiolus_plant", agri_growth: 10 as byte}), <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockPlatinum>, <ore:blockPlatinum>, <ore:blockPlatinum>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockPlatinum>, <mysticalagriculture:crafting:21>, <ore:blockPlatinum>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockPlatinum>, <ore:blockPlatinum>, <ore:blockPlatinum>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:iridium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockIridium>, <ore:blockIridium>, <ore:blockIridium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockIridium>, <mysticalagriculture:crafting:21>, <ore:blockIridium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockIridium>, <ore:blockIridium>, <ore:blockIridium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:enderium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockEnderium>, <ore:blockEnderium>, <ore:blockEnderium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockEnderium>, <mysticalagriculture:crafting:21>, <ore:blockEnderium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockEnderium>, <ore:blockEnderium>, <ore:blockEnderium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:manyullyn_seeds>, [[<ore:essenceSupremium>, <mysticalagriculture:ardite_seeds>, <extendedcrafting:material:36>, <mysticalagriculture:cobalt_seeds>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockManyullyn>, <ore:blockManyullyn>, <ore:blockManyullyn>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockManyullyn>, <mysticalagriculture:crafting:21>, <ore:blockManyullyn>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockManyullyn>, <ore:blockManyullyn>, <ore:blockManyullyn>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:vibrant_alloy_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockVibrantAlloy>, <mysticalagriculture:crafting:21>, <ore:blockVibrantAlloy>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <ore:blockVibrantAlloy>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:end_steel_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockEndSteel>, <ore:blockEndSteel>, <ore:blockEndSteel>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockEndSteel>, <mysticalagriculture:crafting:21>, <ore:blockEndSteel>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockEndSteel>, <ore:blockEndSteel>, <ore:blockEndSteel>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:terrasteel_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <mysticalagriculture:manasteel_seeds>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockTerrasteel>, <mysticalagriculture:crafting:21>, <ore:blockTerrasteel>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <ore:blockTerrasteel>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:refined_obsidian_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockRefinedObsidian>, <ore:blockRefinedObsidian>, <ore:blockRefinedObsidian>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockRefinedObsidian>, <mysticalagriculture:crafting:21>, <ore:blockRefinedObsidian>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockRefinedObsidian>, <ore:blockRefinedObsidian>, <ore:blockRefinedObsidian>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:desh_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockDesh>, <ore:blockDesh>, <ore:blockDesh>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDesh>, <mysticalagriculture:crafting:21>, <ore:blockDesh>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDesh>, <ore:blockDesh>, <ore:blockDesh>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:dreadium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockDreadium>, <ore:blockDreadium>, <ore:blockDreadium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDreadium>, <mysticalagriculture:crafting:21>, <ore:blockDreadium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDreadium>, <ore:blockDreadium>, <ore:blockDreadium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:draconium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDraconium>, <mysticalagriculture:crafting:21>, <ore:blockDraconium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockDraconium>, <ore:blockDraconium>, <ore:blockDraconium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:yellorium_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockYellorium>, <mysticalagriculture:crafting:21>, <ore:blockYellorium>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <ore:blockYellorium>, <ore:blockYellorium>, <ore:blockYellorium>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);
//unsure if need nbt data
mods.extendedcrafting.TableCrafting.addShaped(0, <mysticalagriculture:rock_crystal_seeds>, [[<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>], [<extendedcrafting:material:36>, <astralsorcery:itemrockcrystalsimple>, <astralsorcery:itemrockcrystalsimple>, <astralsorcery:itemrockcrystalsimple>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <astralsorcery:itemrockcrystalsimple>, <mysticalagriculture:crafting:21>, <astralsorcery:itemrockcrystalsimple>, <extendedcrafting:material:36>], [<extendedcrafting:material:36>, <astralsorcery:itemrockcrystalsimple>, <astralsorcery:itemrockcrystalsimple>, <astralsorcery:itemrockcrystalsimple>, <extendedcrafting:material:36>], [<ore:essenceSupremium>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <extendedcrafting:material:36>, <ore:essenceSupremium>]]);