#packmode titan
//quantum compressor
mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:compressor>, [[<ore:ingotBlackIron>, <ore:plateTungsten>, <extendedcrafting:material:10>, <extendedcrafting:material:10>, <extendedcrafting:material:10>, <ore:plateTungsten>, <ore:ingotBlackIron>], [<ore:plateTungsten>, <ore:plateTungsten>, <ore:blockMagnesium>, <ore:blockMagnesium>, <ore:blockMagnesium>, <ore:plateTungsten>, <ore:plateTungsten>], [<extendedcrafting:material:16>, <ore:blockMagnesium>, <galacticraftcore:machine2>, <pneumaticcraft:advanced_air_compressor>, <galacticraftcore:machine2>, <ore:blockMagnesium>, <extendedcrafting:material:16>], [<extendedcrafting:material:16>, <ore:blockMagnesium>, <ae2stuff:inscriber>, <extendedcrafting:frame>, <ae2stuff:inscriber>, <ore:blockMagnesium>, <extendedcrafting:material:16>], [<extendedcrafting:material:16>, <ore:blockMagnesium>, <galacticraftcore:machine2>, <ae2stuff:inscriber>, <galacticraftcore:machine2>, <ore:blockMagnesium>, <extendedcrafting:material:16>], [<ore:plateTungsten>, <ore:plateTungsten>, <ore:blockMagnesium>, <ore:blockMagnesium>, <ore:blockMagnesium>, <ore:plateTungsten>, <ore:plateTungsten>], [<ore:ingotBlackIron>, <ore:plateTungsten>, <extendedcrafting:material:2>, <extendedcrafting:material:2>, <extendedcrafting:material:2>, <ore:plateTungsten>, <ore:ingotBlackIron>]]);

//wand of animation
mods.extendedcrafting.TableCrafting.addShaped(3, <erebus:wand_of_animation>, [[null, null, null, null, <ore:ingotUltimate>, <ore:ingotUltimate>, <ore:blockMirion>], [null, null, null, <ore:ingotCrystalMatrix>, <industrialforegoing:mob_duplicator>, <erebus:materials:64>, <ore:ingotUltimate>], [null, null, null, <ore:ingotCrystalMatrix>, <industrialforegoing:mob_imprisonment_tool>, <industrialforegoing:mob_duplicator>, <ore:ingotUltimate>], [null, null, <ore:plateElectrumFlux>, <ore:blockCrystaltine>, <ore:ingotCrystalMatrix>, <ore:ingotCrystalMatrix>, null], [null, <ore:plateElectrumFlux>, <woot:factory>, <ore:plateElectrumFlux>, null, null, null], [<abyssalcraft:drainstaff:*>, <bloodmagic:sigil_compression>, <ore:plateElectrumFlux>, null, null, null, null], [<astralsorcery:itemshiftingstar>.withTag({astralsorcery: {starAttunement: "astralsorcery.constellation.vicio"}}), <abyssalcraft:drainstaff:*>, null, null, null, null, null]]);

//crystaltine
mods.extendedcrafting.TableCrafting.remove(<extendedcrafting:material:24>);

mods.extendedcrafting.TableCrafting.addShaped(3, <extendedcrafting:material:24>, [[<actuallyadditions:item_crystal_empowered:2>, <ore:gemCrystalFlux>, <ore:ingotCrystallineAlloy>, <ore:gemCrystalFlux>, <ore:ingotCrystallineAlloy>, <ore:gemCrystalFlux>, <actuallyadditions:item_crystal_empowered:2>], [<actuallyadditions:item_crystal_empowered:2>, <ore:itemPulsatingCrystal>, <ore:ingotCrystallinePinkSlime>, <ore:crystalNitrate>, <ore:ingotCrystallinePinkSlime>, <ore:itemPulsatingCrystal>, <actuallyadditions:item_crystal_empowered:2>], [<actuallyadditions:item_crystal_empowered:2>, <ore:itemPulsatingCrystal>, <ore:ingotCrystallinePinkSlime>, <ore:crystalNitrate>, <ore:ingotCrystallinePinkSlime>, <ore:itemPulsatingCrystal>, <actuallyadditions:item_crystal_empowered:2>], [<actuallyadditions:item_crystal_empowered:2>, <ore:gemCrystalFlux>, <ore:ingotCrystallineAlloy>, <ore:gemCrystalFlux>, <ore:ingotCrystallineAlloy>, <ore:gemCrystalFlux>, <actuallyadditions:item_crystal_empowered:2>], [null, null, null, null, null, null, null], [null, null, null, null, null, null, null], [null, null, null, null, null, null, null]]);

//crystal matrix
mods.extendedcrafting.TableCrafting.addShaped(3, <avaritia:resource:1>, [[<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>,<ore:ingotFiery>,<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<ore:netherStar>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<avaritia:resource:0>], [<avaritia:resource:0>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<ore:netherStar>,<ore:ingotCrystaltine>,<ore:ingotCrystaltine>,<avaritia:resource:0>], [<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>,<ore:ingotFiery>,<avaritia:resource:0>,<avaritia:resource:0>,<avaritia:resource:0>], [null,null,null,null,null,null,null], [null,null,null,null,null,null,null], [null,null,null,null,null,null,null]]);

//creative modifier
mods.extendedcrafting.TableCrafting.addShaped(3, <tconstruct:materials:50>, [[<ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <tconstruct:materials:12>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotManyullyn>, <ore:ingotManyullyn>, <ore:ingotCrystaltine>, <ore:ingotManyullyn>, <ore:ingotManyullyn>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <ore:ingotAlubrass>], [<tconstruct:materials:13>, <ore:ingotDesh>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <ore:ingotDesh>, <tconstruct:materials:13>], [<ore:ingotAlubrass>, <ore:ingotDesh>, <ore:ingotManyullyn>, <ore:ingotManyullyn>, <ore:ingotManyullyn>, <ore:ingotDesh>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotDesh>, <forge:bucketfilled>.withTag({FluidName: "lifeessence", Amount: 1000}), <ore:ingotBlackIron>, <forge:bucketfilled>.withTag({FluidName: "lifeessence", Amount: 1000}), <ore:ingotDesh>, <ore:ingotAlubrass>], [<ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <tconstruct:materials:12>, <ore:ingotAlubrass>, <ore:ingotAlubrass>, <ore:ingotAlubrass>]]);

//creative cobble generator
mods.extendedcrafting.TableCrafting.addShaped(3, <compacter:cobbler>,[[<ore:ingotBrickSeared>, <ceramics:unfired_clay:5>, <ceramics:unfired_clay:5>, <tp:emerald_cobblegen_block>, <ceramics:unfired_clay:5>, <ceramics:unfired_clay:5>, <ore:ingotBrickSeared>], [<mysticalagriculture:ultimate_furnace>, <mysticalagradditions:stuff:69>, <ore:ingotCrystaltine>, <pneumaticcraft:network_component:3>, <ore:ingotCrystaltine>, <mysticalagradditions:stuff:69>, <mysticalagriculture:ultimate_furnace>], [<ore:ingotBrickSeared>, <ore:ingotCrystaltine>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <ore:ingotCrystaltine>, <ore:ingotBrickSeared>], [<contenttweaker:neutral_steel_4>, <pneumaticcraft:network_component:3>, <tp:lava_infused_stone>, <ore:compressed6xCobblestone>, <tp:lava_infused_stone>, <pneumaticcraft:network_component:3>, <contenttweaker:neutral_steel_4>], [<ore:ingotBrickSeared>, <ore:ingotCrystaltine>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <ore:ingotCrystaltine>, <ore:ingotBrickSeared>], [<furnaceoverhaul:zenith_furnace>, <mysticalagradditions:stuff:69>, <ore:ingotCrystaltine>, <pneumaticcraft:network_component:3>, <ore:ingotCrystaltine>, <mysticalagradditions:stuff:69>, <furnaceoverhaul:zenith_furnace>], [<tp:blaze_cobblegen_block>, <tp:diamond_cobblegen_block>, <tp:iron_cobblegen_block>, <tp:cobblegen_block>, <tp:iron_cobblegen_block>, <tp:diamond_cobblegen_block>, <tp:blaze_cobblegen_block>]]);