#packmode normal titan kappa
//cobalt armor
mods.armorplus.HighTechBench.addShaped(<armorplus:cobalt_helmet>, [[<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,<ore:ingotCobalt>,<actuallyadditions:item_helm_crystal_green>.anyDamage(),<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,null,null,null,<ore:ingotCobalt>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:cobalt_chestplate>, [[<ore:ingotCobalt>,null,<actuallyadditions:item_chest_crystal_green>.anyDamage(),null,<ore:ingotCobalt>], [<ore:ingotCobalt>,null,null,null,<ore:ingotCobalt>], [<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:cobalt_leggings>, [[<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,null,<actuallyadditions:item_pants_crystal_green>.anyDamage(),null,<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,null,null,null,<ore:ingotCobalt>], [<ore:ingotCobalt>,null,null,null,<ore:ingotCobalt>], [<ore:ingotCobalt>,null,null,null,<ore:ingotCobalt>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:cobalt_boots>, [[<ore:ingotCobalt>,<ore:ingotCobalt>,<actuallyadditions:item_boots_crystal_green>.anyDamage(),<ore:ingotCobalt>,<ore:ingotCobalt>], [<ore:ingotCobalt>,<ore:ingotCobalt>,null,<ore:ingotCobalt>,<ore:ingotCobalt>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//ardite armor
mods.armorplus.HighTechBench.addShaped(<armorplus:ardite_helmet>, [[<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,<ore:ingotArdite>,<armorplus:cobalt_helmet>.anyDamage(),<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,null,null,null,<ore:ingotArdite>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:ardite_chestplate>, [[<ore:ingotArdite>,null,<armorplus:cobalt_chestplate>.anyDamage(),null,<ore:ingotArdite>], [<ore:ingotArdite>,null,null,null,<ore:ingotArdite>], [<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:ardite_leggings>, [[<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,null,<armorplus:cobalt_leggings>.anyDamage(),null,<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,null,null,null,<ore:ingotArdite>], [<ore:ingotArdite>,null,null,null,<ore:ingotArdite>], [<ore:ingotArdite>,null,null,null,<ore:ingotArdite>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:ardite_boots>, [[<ore:ingotArdite>,<ore:ingotArdite>,<armorplus:cobalt_boots>.anyDamage(),<ore:ingotArdite>,<ore:ingotArdite>], [<ore:ingotArdite>,<ore:ingotArdite>,null,<ore:ingotArdite>,<ore:ingotArdite>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//knightslime armor
mods.armorplus.HighTechBench.addShaped(<armorplus:knight_slime_helmet>, [[<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,<ore:ingotKnightslime>,<armorplus:ardite_helmet>.anyDamage(),<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,null,null,null,<ore:ingotKnightslime>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:knight_slime_chestplate>, [[<ore:ingotKnightslime>,null,<armorplus:ardite_chestplate>.anyDamage(),null,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,null,null,null,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:knight_slime_leggings>, [[<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,null,<armorplus:ardite_leggings>.anyDamage(),null,<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,null,null,null,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,null,null,null,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,null,null,null,<ore:ingotKnightslime>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:knight_slime_boots>, [[<ore:ingotKnightslime>,<ore:ingotKnightslime>,<armorplus:ardite_boots>.anyDamage(),<ore:ingotKnightslime>,<ore:ingotKnightslime>], [<ore:ingotKnightslime>,<ore:ingotKnightslime>,null,<ore:ingotKnightslime>,<ore:ingotKnightslime>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//arctic armor
recipes.remove(<twilightforest:arctic_helmet>);
recipes.remove(<twilightforest:arctic_chestplate>);
recipes.remove(<twilightforest:arctic_leggings>);
recipes.remove(<twilightforest:arctic_boots>);

mods.armorplus.HighTechBench.addShaped(<twilightforest:arctic_helmet>, [[<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,<ore:furArctic>,<armorplus:knight_slime_helmet>.anyDamage(),<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,null,null,null,<ore:furArctic>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:arctic_chestplate>, [[<ore:furArctic>,null,<armorplus:knight_slime_chestplate>.anyDamage(),null,<ore:furArctic>], [<ore:furArctic>,null,null,null,<ore:furArctic>], [<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:arctic_leggings>, [[<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,null,<armorplus:knight_slime_leggings>.anyDamage(),null,<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,null,null,null,<ore:furArctic>], [<ore:furArctic>,null,null,null,<ore:furArctic>], [<ore:furArctic>,null,null,null,<ore:furArctic>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:arctic_boots>, [[<ore:furArctic>,<ore:furArctic>,<armorplus:knight_slime_boots>.anyDamage(),<ore:furArctic>,<ore:furArctic>], [<ore:furArctic>,<ore:furArctic>,null,<ore:furArctic>,<ore:furArctic>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//ironwood armor
recipes.remove(<twilightforest:ironwood_boots>);
recipes.remove(<twilightforest:ironwood_leggings>);
recipes.remove(<twilightforest:ironwood_chestplate>);
recipes.remove(<twilightforest:ironwood_helmet>);

mods.armorplus.HighTechBench.addShaped(<twilightforest:ironwood_helmet>.withTag({ench:[{lvl:1,id:6}]}), [[<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,<ore:ingotIronwood>,<twilightforest:arctic_helmet>.anyDamage(),<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,null,null,null,<ore:ingotIronwood>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:ironwood_chestplate>.withTag({ench:[{lvl:1,id:0}]}), [[<ore:ingotIronwood>,null,<twilightforest:arctic_chestplate>.anyDamage(),null,<ore:ingotIronwood>], [<ore:ingotIronwood>,null,null,null,<ore:ingotIronwood>], [<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:ironwood_leggings>.withTag({ench:[{lvl:1,id:0}]}), [[<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,null,<twilightforest:arctic_leggings>.anyDamage(),null,<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,null,null,null,<ore:ingotIronwood>], [<ore:ingotIronwood>,null,null,null,<ore:ingotIronwood>], [<ore:ingotIronwood>,null,null,null,<ore:ingotIronwood>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:ironwood_boots>.withTag({ench:[{lvl:1,id:2}]}), [[<ore:ingotIronwood>,<ore:ingotIronwood>,<twilightforest:arctic_boots>.anyDamage(),<ore:ingotIronwood>,<ore:ingotIronwood>], [<ore:ingotIronwood>,<ore:ingotIronwood>,null,<ore:ingotIronwood>,<ore:ingotIronwood>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//manyullyn armor
mods.armorplus.HighTechBench.addShaped(<armorplus:manyullyn_helmet>, [[<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,<ore:ingotManyullyn>,<twilightforest:ironwood_helmet>.withTag({ench:[{lvl:1,id:6}]}).anyDamage(),<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,null,null,null,<ore:ingotManyullyn>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:manyullyn_chestplate>, [[<ore:ingotManyullyn>,null,<twilightforest:ironwood_chestplate>.withTag({ench:[{lvl:1,id:0}]}).anyDamage(),null,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,null,null,null,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:manyullyn_leggings>, [[<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,null,<twilightforest:ironwood_leggings>.withTag({ench:[{lvl:1,id:0}]}).anyDamage(),null,<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,null,null,null,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,null,null,null,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,null,null,null,<ore:ingotManyullyn>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:manyullyn_boots>, [[<ore:ingotManyullyn>,<ore:ingotManyullyn>,<twilightforest:ironwood_boots>.withTag({ench:[{lvl:1,id:2}]}).anyDamage(),<ore:ingotManyullyn>,<ore:ingotManyullyn>], [<ore:ingotManyullyn>,<ore:ingotManyullyn>,null,<ore:ingotManyullyn>,<ore:ingotManyullyn>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//hard carbon armor
recipes.remove(<nuclearcraft:helm_hard_carbon>);
recipes.remove(<nuclearcraft:chest_hard_carbon>);
recipes.remove(<nuclearcraft:legs_hard_carbon>);
recipes.remove(<nuclearcraft:boots_hard_carbon>);

mods.armorplus.HighTechBench.addShaped(<nuclearcraft:helm_hard_carbon>, [[<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<armorplus:manyullyn_helmet>.anyDamage(),<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,null,null,null,<ore:ingotHardCarbon>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:chest_hard_carbon>, [[<ore:ingotHardCarbon>,null,<armorplus:manyullyn_chestplate>.anyDamage(),null,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,null,null,null,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:legs_hard_carbon>, [[<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,null,<armorplus:manyullyn_leggings>.anyDamage(),null,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,null,null,null,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,null,null,null,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,null,null,null,<ore:ingotHardCarbon>]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:boots_hard_carbon>, [[<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,<armorplus:manyullyn_boots>.anyDamage(),<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [<ore:ingotHardCarbon>,<ore:ingotHardCarbon>,null,<ore:ingotHardCarbon>,<ore:ingotHardCarbon>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//glowstone armor
recipes.remove(<mekanismtools:glowstoneboots>);
recipes.remove(<mekanismtools:glowstoneleggings>);
recipes.remove(<mekanismtools:glowstonechestplate>);
recipes.remove(<mekanismtools:glowstonehelmet>);

mods.armorplus.HighTechBench.addShaped(<mekanismtools:glowstonehelmet>, [[<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<nuclearcraft:helm_hard_carbon>.anyDamage(),<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,null,null,null,<ore:ingotRefinedGlowstone>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<mekanismtools:glowstonechestplate>, [[<ore:ingotRefinedGlowstone>,null,<nuclearcraft:chest_hard_carbon>.anyDamage(),null,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,null,null,null,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>]]);
mods.armorplus.HighTechBench.addShaped(<mekanismtools:glowstoneleggings>, [[<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,null,<nuclearcraft:legs_hard_carbon>.anyDamage(),null,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,null,null,null,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,null,null,null,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,null,null,null,<ore:ingotRefinedGlowstone>]]);
mods.armorplus.HighTechBench.addShaped(<mekanismtools:glowstoneboots>, [[<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,<nuclearcraft:boots_hard_carbon>.anyDamage(),<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>,null,<ore:ingotRefinedGlowstone>,<ore:ingotRefinedGlowstone>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//tough alloy armor
recipes.remove(<nuclearcraft:helm_tough>);
recipes.remove(<nuclearcraft:chest_tough>);
recipes.remove(<nuclearcraft:legs_tough>);
recipes.remove(<nuclearcraft:boots_tough>);

mods.armorplus.HighTechBench.addShaped(<nuclearcraft:helm_tough>, [[<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,<ore:ingotTough>,<mekanismtools:glowstonehelmet>.anyDamage(),<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,null,null,null,<ore:ingotTough>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:chest_tough>, [[<ore:ingotTough>,null,<mekanismtools:glowstonechestplate>.anyDamage(),null,<ore:ingotTough>], [<ore:ingotTough>,null,null,null,<ore:ingotTough>], [<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:legs_tough>, [[<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,null,<mekanismtools:glowstoneleggings>.anyDamage(),null,<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,null,null,null,<ore:ingotTough>], [<ore:ingotTough>,null,null,null,<ore:ingotTough>], [<ore:ingotTough>,null,null,null,<ore:ingotTough>]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:boots_tough>, [[<ore:ingotTough>,<ore:ingotTough>,<mekanismtools:glowstoneboots>.anyDamage(),<ore:ingotTough>,<ore:ingotTough>], [<ore:ingotTough>,<ore:ingotTough>,null,<ore:ingotTough>,<ore:ingotTough>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//steeleaf armor
recipes.remove(<twilightforest:steeleaf_helmet>);
recipes.remove(<twilightforest:steeleaf_chestplate>);
recipes.remove(<twilightforest:steeleaf_leggings>);
recipes.remove(<twilightforest:steeleaf_boots>);

mods.armorplus.HighTechBench.addShaped(<twilightforest:steeleaf_helmet>.withTag({ench:[{lvl:2,id:4}]}), [[<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<nuclearcraft:helm_tough>.anyDamage(),<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,null,null,null,<ore:ingotSteeleaf>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:steeleaf_chestplate>.withTag({ench:[{lvl:2,id:3}]}), [[<ore:ingotSteeleaf>,null,<nuclearcraft:chest_tough>.anyDamage(),null,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,null,null,null,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:steeleaf_leggings>.withTag({ench:[{lvl:2,id:1}]}), [[<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,null,<nuclearcraft:legs_tough>.anyDamage(),null,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,null,null,null,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,null,null,null,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,null,null,null,<ore:ingotSteeleaf>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:steeleaf_boots>.withTag({ench:[{lvl:2,id:2}]}), [[<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,<nuclearcraft:boots_tough>.anyDamage(),<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [<ore:ingotSteeleaf>,<ore:ingotSteeleaf>,null,<ore:ingotSteeleaf>,<ore:ingotSteeleaf>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//knightly armor
recipes.remove(<twilightforest:knightmetal_helmet>);
recipes.remove(<twilightforest:knightmetal_chestplate>);
recipes.remove(<twilightforest:knightmetal_leggings>);
recipes.remove(<twilightforest:knightmetal_boots>);

mods.armorplus.HighTechBench.addShaped(<twilightforest:knightmetal_helmet>, [[<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<twilightforest:steeleaf_helmet>.withTag({ench:[{lvl:2,id:4}]}).anyDamage(),<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,null,null,null,<ore:ingotKnightmetal>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:knightmetal_chestplate>, [[<ore:ingotKnightmetal>,null,<twilightforest:steeleaf_chestplate>.withTag({ench:[{lvl:2,id:3}]}).anyDamage(),null,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,null,null,null,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:knightmetal_leggings>, [[<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,null,<twilightforest:steeleaf_leggings>.withTag({ench:[{lvl:2,id:1}]}).anyDamage(),null,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,null,null,null,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,null,null,null,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,null,null,null,<ore:ingotKnightmetal>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:knightmetal_boots>, [[<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,<twilightforest:steeleaf_boots>.withTag({ench:[{lvl:2,id:2}]}).anyDamage(),<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [<ore:ingotKnightmetal>,<ore:ingotKnightmetal>,null,<ore:ingotKnightmetal>,<ore:ingotKnightmetal>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//yeti armor
recipes.remove(<twilightforest:yeti_helmet>);
recipes.remove(<twilightforest:yeti_chestplate>);
recipes.remove(<twilightforest:yeti_leggings>);
recipes.remove(<twilightforest:yeti_boots>);

mods.armorplus.HighTechBench.addShaped(<twilightforest:yeti_helmet>.withTag({ench:[{lvl:2,id:0}]}), [[<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:knightmetal_helmet>.anyDamage(),<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,null,null,null,<twilightforest:alpha_fur>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:yeti_chestplate>.withTag({ench:[{lvl:2,id:0}]}), [[<twilightforest:alpha_fur>,null,<twilightforest:knightmetal_chestplate>.anyDamage(),null,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,null,null,null,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:yeti_leggings>.withTag({ench:[{lvl:2,id:0}]}), [[<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,null,<twilightforest:knightmetal_leggings>.anyDamage(),null,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,null,null,null,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,null,null,null,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,null,null,null,<twilightforest:alpha_fur>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:yeti_boots>.withTag({ench:[{lvl:2,id:0}, {lvl:4,id:2}]}), [[<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,<twilightforest:knightmetal_boots>.anyDamage(),<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [<twilightforest:alpha_fur>,<twilightforest:alpha_fur>,null,<twilightforest:alpha_fur>,<twilightforest:alpha_fur>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//abyssalnite armor
recipes.remove(<abyssalcraft:ahelmet>);
recipes.remove(<abyssalcraft:aplate>);
recipes.remove(<abyssalcraft:alegs>);
recipes.remove(<abyssalcraft:aboots>);

mods.armorplus.HighTechBench.addShaped(<abyssalcraft:ahelmet>, [[<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<twilightforest:yeti_helmet>.withTag({ench:[{lvl:2,id:0}]}).anyDamage(),<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,null,null,null,<ore:ingotAbyssalnite>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:aplate>, [[<ore:ingotAbyssalnite>,null,<twilightforest:yeti_chestplate>.withTag({ench:[{lvl:2,id:0}]}).anyDamage(),null,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,null,null,null,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:alegs>, [[<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,null,<twilightforest:yeti_leggings>.withTag({ench:[{lvl:2,id:0}]}).anyDamage(),null,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,null,null,null,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,null,null,null,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,null,null,null,<ore:ingotAbyssalnite>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:aboots>, [[<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,<twilightforest:yeti_boots>.withTag({ench:[{lvl:2,id:0}, {lvl:4,id:2}]}).anyDamage(),<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>,null,<ore:ingotAbyssalnite>,<ore:ingotAbyssalnite>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//refined coralium armor
recipes.remove(<abyssalcraft:corhelmet>);
recipes.remove(<abyssalcraft:corplate>);
recipes.remove(<abyssalcraft:corlegs>);
recipes.remove(<abyssalcraft:corboots>);

mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corhelmet>, [[<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<abyssalcraft:dhelmet>.anyDamage(),<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,null,null,null,<ore:ingotLiquifiedCoralium>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corplate>, [[<ore:ingotLiquifiedCoralium>,null,<abyssalcraft:dplate>.anyDamage(),null,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,null,null,null,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corlegs>, [[<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,null,<abyssalcraft:dlegs>.anyDamage(),null,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,null,null,null,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,null,null,null,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,null,null,null,<ore:ingotLiquifiedCoralium>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corboots>, [[<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,<abyssalcraft:dboots>.anyDamage(),<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>,null,<ore:ingotLiquifiedCoralium>,<ore:ingotLiquifiedCoralium>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//dreadium armor
recipes.remove(<abyssalcraft:dreadiumhelmet>);
recipes.remove(<abyssalcraft:dreadiumplate>);
recipes.remove(<abyssalcraft:dreadiumlegs>);
recipes.remove(<abyssalcraft:dreadiumboots>);

mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumhelmet>, [[<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,<ore:ingotDreadium>,<abyssalcraft:corhelmet>.anyDamage(),<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,null,null,null,<ore:ingotDreadium>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumplate>, [[<ore:ingotDreadium>,null,<abyssalcraft:corplate>.anyDamage(),null,<ore:ingotDreadium>], [<ore:ingotDreadium>,null,null,null,<ore:ingotDreadium>], [<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumlegs>, [[<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,null,<abyssalcraft:corlegs>.anyDamage(),null,<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,null,null,null,<ore:ingotDreadium>], [<ore:ingotDreadium>,null,null,null,<ore:ingotDreadium>], [<ore:ingotDreadium>,null,null,null,<ore:ingotDreadium>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumboots>, [[<ore:ingotDreadium>,<ore:ingotDreadium>,<abyssalcraft:corboots>.anyDamage(),<ore:ingotDreadium>,<ore:ingotDreadium>], [<ore:ingotDreadium>,<ore:ingotDreadium>,null,<ore:ingotDreadium>,<ore:ingotDreadium>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//boron nitride armor
recipes.remove(<nuclearcraft:helm_boron_nitride>);
recipes.remove(<nuclearcraft:chest_boron_nitride>);
recipes.remove(<nuclearcraft:legs_boron_nitride>);
recipes.remove(<nuclearcraft:boots_boron_nitride>);

mods.armorplus.HighTechBench.addShaped(<nuclearcraft:helm_boron_nitride>, [[<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,<ore:gemBoronNitride>,<abyssalcraft:dreadiumhelmet>.anyDamage(),<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,null,null,null,<ore:gemBoronNitride>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:chest_boron_nitride>, [[<ore:gemBoronNitride>,null,<abyssalcraft:dreadiumplate>.anyDamage(),null,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,null,null,null,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:legs_boron_nitride>, [[<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,null,<abyssalcraft:dreadiumlegs>.anyDamage(),null,<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,null,null,null,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,null,null,null,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,null,null,null,<ore:gemBoronNitride>]]);
mods.armorplus.HighTechBench.addShaped(<nuclearcraft:boots_boron_nitride>, [[<ore:gemBoronNitride>,<ore:gemBoronNitride>,<abyssalcraft:dreadiumboots>.anyDamage(),<ore:gemBoronNitride>,<ore:gemBoronNitride>], [<ore:gemBoronNitride>,<ore:gemBoronNitride>,null,<ore:gemBoronNitride>,<ore:gemBoronNitride>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//infused lava armor
mods.armorplus.HighTechBench.addShaped(<armorplus:infused_lava_helmet>, [[<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<nuclearcraft:helm_boron_nitride>.anyDamage(),<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,null,null,null,<ore:ingotInfusedLavaCrystal>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:infused_lava_chestplate>, [[<ore:ingotInfusedLavaCrystal>,null,<nuclearcraft:chest_boron_nitride>.anyDamage(),null,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,null,null,null,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:infused_lava_leggings>, [[<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,null,<nuclearcraft:legs_boron_nitride>.anyDamage(),null,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,null,null,null,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,null,null,null,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,null,null,null,<ore:ingotInfusedLavaCrystal>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:infused_lava_boots>, [[<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,<nuclearcraft:boots_boron_nitride>.anyDamage(),<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>,null,<ore:ingotInfusedLavaCrystal>,<ore:ingotInfusedLavaCrystal>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//dreadium samurai armor
recipes.remove(<abyssalcraft:dreadiumsamuraihelmet>);
recipes.remove(<abyssalcraft:dreadiumsamuraiplate>);
recipes.remove(<abyssalcraft:dreadiumsamurailegs>);
recipes.remove(<abyssalcraft:dreadiumsamuraiboots>);

mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumsamuraihelmet>, [[<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<armorplus:infused_lava_helmet>.anyDamage(),<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,null,null,null,<abyssalcraft:dreadplate>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumsamuraiplate>, [[<abyssalcraft:dreadplate>,null,<armorplus:infused_lava_chestplate>.anyDamage(),null,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,null,null,null,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumsamurailegs>, [[<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,null,<armorplus:infused_lava_leggings>.anyDamage(),null,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,null,null,null,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,null,null,null,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,null,null,null,<abyssalcraft:dreadplate>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:dreadiumsamuraiboots>, [[<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,<armorplus:infused_lava_boots>.anyDamage(),<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>,null,<abyssalcraft:dreadplate>,<abyssalcraft:dreadplate>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//ethaxium armor
recipes.remove(<abyssalcraft:ethaxiumhelmet>);
recipes.remove(<abyssalcraft:ethaxiumplate>);
recipes.remove(<abyssalcraft:ethaxiumlegs>);
recipes.remove(<abyssalcraft:ethaxiumboots>);

mods.armorplus.HighTechBench.addShaped(<abyssalcraft:ethaxiumhelmet>, [[<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,<ore:ingotEthaxium>,<abyssalcraft:dreadiumsamuraihelmet>.anyDamage(),<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,null,null,null,<ore:ingotEthaxium>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:ethaxiumplate>, [[<ore:ingotEthaxium>,null,<abyssalcraft:dreadiumsamuraiplate>.anyDamage(),null,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,null,null,null,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:ethaxiumlegs>, [[<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,null,<abyssalcraft:dreadiumsamurailegs>.anyDamage(),null,<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,null,null,null,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,null,null,null,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,null,null,null,<ore:ingotEthaxium>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:ethaxiumboots>, [[<ore:ingotEthaxium>,<ore:ingotEthaxium>,<abyssalcraft:dreadiumsamuraiboots>.anyDamage(),<ore:ingotEthaxium>,<ore:ingotEthaxium>], [<ore:ingotEthaxium>,<ore:ingotEthaxium>,null,<ore:ingotEthaxium>,<ore:ingotEthaxium>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//guardian armor
mods.armorplus.HighTechBench.addShaped(<armorplus:guardian_helmet>, [[<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,<ore:scaleGuardian>,<abyssalcraft:ethaxiumhelmet>.anyDamage(),<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,null,null,null,<ore:scaleGuardian>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:guardian_chestplate>, [[<ore:scaleGuardian>,null,<abyssalcraft:ethaxiumplate>.anyDamage(),null,<ore:scaleGuardian>], [<ore:scaleGuardian>,null,null,null,<ore:scaleGuardian>], [<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:guardian_leggings>, [[<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,null,<abyssalcraft:ethaxiumlegs>.anyDamage(),null,<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,null,null,null,<ore:scaleGuardian>], [<ore:scaleGuardian>,null,null,null,<ore:scaleGuardian>], [<ore:scaleGuardian>,null,null,null,<ore:scaleGuardian>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:guardian_boots>, [[<ore:scaleGuardian>,<ore:scaleGuardian>,<abyssalcraft:ethaxiumboots>.anyDamage(),<ore:scaleGuardian>,<ore:scaleGuardian>], [<ore:scaleGuardian>,<ore:scaleGuardian>,null,<ore:scaleGuardian>,<ore:scaleGuardian>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//super star armor
mods.armorplus.HighTechBench.addShaped(<armorplus:super_star_helmet>, [[<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,<ore:witherBone>,<armorplus:guardian_helmet>.anyDamage(),<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,null,null,null,<ore:witherBone>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:super_star_chestplate>, [[<ore:witherBone>,null,<armorplus:guardian_chestplate>.anyDamage(),null,<ore:witherBone>], [<ore:witherBone>,null,null,null,<ore:witherBone>], [<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:super_star_leggings>, [[<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,null,<armorplus:guardian_leggings>.anyDamage(),null,<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,null,null,null,<ore:witherBone>], [<ore:witherBone>,null,null,null,<ore:witherBone>], [<ore:witherBone>,null,null,null,<ore:witherBone>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:super_star_boots>, [[<ore:witherBone>,<ore:witherBone>,<armorplus:guardian_boots>.anyDamage(),<ore:witherBone>,<ore:witherBone>], [<ore:witherBone>,<ore:witherBone>,null,<ore:witherBone>,<ore:witherBone>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//fiery armor
recipes.remove(<twilightforest:fiery_helmet>);
recipes.remove(<twilightforest:fiery_chestplate>);
recipes.remove(<twilightforest:fiery_leggings>);
recipes.remove(<twilightforest:fiery_boots>);

mods.armorplus.HighTechBench.addShaped(<twilightforest:fiery_helmet>, [[<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,<ore:ingotFiery>,<armorplus:super_star_helmet>.anyDamage(),<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,null,null,null,<ore:ingotFiery>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:fiery_chestplate>, [[<ore:ingotFiery>,null,<armorplus:super_star_chestplate>.anyDamage(),null,<ore:ingotFiery>], [<ore:ingotFiery>,null,null,null,<ore:ingotFiery>], [<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:fiery_leggings>, [[<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,null,<armorplus:super_star_leggings>.anyDamage(),null,<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,null,null,null,<ore:ingotFiery>], [<ore:ingotFiery>,null,null,null,<ore:ingotFiery>], [<ore:ingotFiery>,null,null,null,<ore:ingotFiery>]]);
mods.armorplus.HighTechBench.addShaped(<twilightforest:fiery_boots>, [[<ore:ingotFiery>,<ore:ingotFiery>,<armorplus:super_star_boots>.anyDamage(),<ore:ingotFiery>,<ore:ingotFiery>], [<ore:ingotFiery>,<ore:ingotFiery>,null,<ore:ingotFiery>,<ore:ingotFiery>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//plated coralium armor
recipes.remove(<abyssalcraft:corhelmetp>);
recipes.remove(<abyssalcraft:corplatep>);
recipes.remove(<abyssalcraft:corlegsp>);
recipes.remove(<abyssalcraft:corbootsp>);

mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corhelmetp>, [[<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,<abyssalcraft:platec>,<twilightforest:fiery_helmet>.anyDamage(),<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,null,null,null,<abyssalcraft:platec>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corplatep>, [[<abyssalcraft:platec>,null,<twilightforest:fiery_chestplate>.anyDamage(),null,<abyssalcraft:platec>], [<abyssalcraft:platec>,null,null,null,<abyssalcraft:platec>], [<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corlegsp>, [[<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,null,<twilightforest:fiery_leggings>.anyDamage(),null,<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,null,null,null,<abyssalcraft:platec>], [<abyssalcraft:platec>,null,null,null,<abyssalcraft:platec>], [<abyssalcraft:platec>,null,null,null,<abyssalcraft:platec>]]);
mods.armorplus.HighTechBench.addShaped(<abyssalcraft:corbootsp>, [[<abyssalcraft:platec>,<abyssalcraft:platec>,<twilightforest:fiery_boots>.anyDamage(),<abyssalcraft:platec>,<abyssalcraft:platec>], [<abyssalcraft:platec>,<abyssalcraft:platec>,null,<abyssalcraft:platec>,<abyssalcraft:platec>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//refined obsidian armor
recipes.remove(<mekanismtools:obsidianhelmet>);
recipes.remove(<mekanismtools:obsidianchestplate>);
recipes.remove(<mekanismtools:obsidianleggings>);
recipes.remove(<mekanismtools:obsidianboots>);

mods.armorplus.HighTechBench.addShaped(<mekanismtools:obsidianhelmet>, [[<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<abyssalcraft:corhelmetp>.anyDamage(),<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,null,null,null,<ore:ingotRefinedObsidian>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<mekanismtools:obsidianchestplate>, [[<ore:ingotRefinedObsidian>,null,<abyssalcraft:corplatep>.anyDamage(),null,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,null,null,null,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>]]);
mods.armorplus.HighTechBench.addShaped(<mekanismtools:obsidianleggings>, [[<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,null,<abyssalcraft:corlegsp>.anyDamage(),null,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,null,null,null,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,null,null,null,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,null,null,null,<ore:ingotRefinedObsidian>]]);
mods.armorplus.HighTechBench.addShaped(<mekanismtools:obsidianboots>, [[<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,<abyssalcraft:corbootsp>.anyDamage(),<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>,null,<ore:ingotRefinedObsidian>,<ore:ingotRefinedObsidian>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);

//ender dragon armor
mods.armorplus.HighTechBench.addShaped(<armorplus:ender_dragon_helmet>, [[<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<mekanismtools:obsidianhelmet>.anyDamage(),<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,null,null,null,<ore:scaleEnderDragon>], [null,null,null,null,null], [null,null,null,null,null]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:ender_dragon_chestplate>, [[<ore:scaleEnderDragon>,null,<mekanismtools:obsidianchestplate>.anyDamage(),null,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,null,null,null,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:ender_dragon_leggings>, [[<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,null,<mekanismtools:obsidianleggings>.anyDamage(),null,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,null,null,null,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,null,null,null,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,null,null,null,<ore:scaleEnderDragon>]]);
mods.armorplus.HighTechBench.addShaped(<armorplus:ender_dragon_boots>, [[<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,<mekanismtools:obsidianboots>.anyDamage(),<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [<ore:scaleEnderDragon>,<ore:scaleEnderDragon>,null,<ore:scaleEnderDragon>,<ore:scaleEnderDragon>], [null,null,null,null,null], [null,null,null,null,null], [null,null,null,null,null]]);