#packmode titan
mods.astralsorcery.Altar.addTraitAltarRecipe("astralsorcery:shaped/astralsorcery:bloodcrystal", <bloodmagic:decorative_brick:2> * 4, 2000, 10, [<lordcraft:crystal_basic_cosmic>, <lordcraft:crystal_basic_cosmic>, <lordcraft:crystal_basic_cosmic>, <lordcraft:crystal_basic_cosmic>, <astralsorcery:itemcelestialcrystal:0>, <lordcraft:crystal_basic_cosmic>, <lordcraft:crystal_basic_cosmic>, <lordcraft:crystal_basic_cosmic>, <lordcraft:crystal_basic_cosmic>,<ore:gemRuby>, <ore:gemRuby>, <ore:gemRuby>, <ore:gemRuby>,<ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>], "astralsorcery.constellation.octans");

mods.astralsorcery.Altar.addDiscoveryAltarRecipe("po3:shaped/internal/altar/mekanism_installer_2", <mekanism:tierinstaller:2>, 200, 200, [<ore:alloyElite>, <ore:circuitElite>, <ore:alloyElite>,<ore:ingotGold>, <mekanism:tierinstaller:1>, <ore:ingotGold>, <ore:alloyElite>, <ore:circuitElite>, <ore:alloyElite>]);

mods.astralsorcery.Altar.addConstellationAltarRecipe("astralsorcery:shaped/ct/null",<aroma1997sdimension:miningmultitool>, 2000, 10, [<erebus:glow_gem_active>, <astralsorcery:itemcraftingcomponent:4>, <erebus:glow_gem_active>,<erebus:glow_gem_active>, <astralsorcery:itemcraftingcomponent:4>, <erebus:glow_gem_active>,<ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>,<erebus:materials:12>, <erebus:materials:12>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>,<erebus:materials:12>, <erebus:materials:12>,<erebus:materials:12>, <erebus:materials:12>,<ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>,<ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>]);
 
//seeds
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/goldseeds", <mysticalagriculture:gold_seeds>, 500, 300, [<ore:ingotGold>, <ore:dustAstralStarmetal>, <ore:ingotGold>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotGold>, <ore:dustAstralStarmetal>, <ore:ingotGold>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/lapisseeds", <mysticalagriculture:lapis_lazuli_seeds>, 500, 300, [<ore:gemLapis>, <ore:dustAstralStarmetal>, <ore:gemLapis>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:gemLapis>, <ore:dustAstralStarmetal>, <ore:gemLapis>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/endseeds", <mysticalagriculture:end_seeds>, 500, 300, [<mysticalagriculture:crafting:9>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:9>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:9>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:9>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/xpseeds", <mysticalagriculture:experience_seeds>, 500, 300, [<mysticalagriculture:chunk:5>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:5>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:5>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:5>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/blazeseeds", <mysticalagriculture:blaze_seeds>, 500, 300, [<mysticalagriculture:chunk:17>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:17>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:17>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:17>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/ghastseeds", <mysticalagriculture:ghast_seeds>, 500, 300, [<mysticalagriculture:chunk:18>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:18>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:18>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:18>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/endermanseeds", <mysticalagriculture:enderman_seeds>, 500, 300, [<mysticalagriculture:chunk:19>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:19>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:19>, <ore:dustAstralStarmetal>, <mysticalagriculture:chunk:19>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/steelseeds", <mysticalagriculture:steel_seeds>, 500, 300, [<ore:ingotSteel>, <ore:dustAstralStarmetal>, <ore:ingotSteel>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotSteel>, <ore:dustAstralStarmetal>, <ore:ingotSteel>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/nickelseeds", <mysticalagriculture:nickel_seeds>, 500, 300, [<ore:ingotNickel>, <ore:dustAstralStarmetal>, <ore:ingotNickel>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotNickel>, <ore:dustAstralStarmetal>, <ore:ingotNickel>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/constantanseeds", <mysticalagriculture:constantan_seeds>, 500, 300, [<ore:ingotConstantan>, <ore:dustAstralStarmetal>, <ore:ingotConstantan>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotConstantan>, <ore:dustAstralStarmetal>, <ore:ingotConstantan>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/electrumseeds", <mysticalagriculture:electrum_seeds>, 500, 300, [<ore:ingotElectrum>, <ore:dustAstralStarmetal>, <ore:ingotElectrum>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotElectrum>, <ore:dustAstralStarmetal>, <ore:ingotElectrum>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/invarseeds", <mysticalagriculture:invar_seeds>, 500, 300, [<ore:ingotInvar>, <ore:dustAstralStarmetal>, <ore:ingotInvar>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotInvar>, <ore:dustAstralStarmetal>, <ore:ingotInvar>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/mithrilseeds", <mysticalagriculture:mithril_seeds>, 500, 300, [<ore:ingotMithril>, <ore:dustAstralStarmetal>, <ore:ingotMithril>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotMithril>, <ore:dustAstralStarmetal>, <ore:ingotMithril>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/rubyseeds", <mysticalagriculture:ruby_seeds>, 500, 300, [<ore:gemRuby>, <ore:dustAstralStarmetal>, <ore:gemRuby>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:gemRuby>, <ore:dustAstralStarmetal>, <ore:gemRuby>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/sapphireseeds", <mysticalagriculture:sapphire_seeds>, 500, 300, [<ore:gemSapphire>, <ore:dustAstralStarmetal>, <ore:gemSapphire>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:gemSapphire>, <ore:dustAstralStarmetal>, <ore:gemSapphire>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/peridotseeds", <mysticalagriculture:peridot_seeds>, 500, 300, [<ore:gemPeridot>, <ore:dustAstralStarmetal>, <ore:gemPeridot>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:gemPeridot>, <ore:dustAstralStarmetal>, <ore:gemPeridot>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/signalumseeds", <mysticalagriculture:signalum_seeds>, 500, 300, [<ore:ingotSignalum>, <ore:dustAstralStarmetal>, <ore:ingotSignalum>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotSignalum>, <ore:dustAstralStarmetal>, <ore:ingotSignalum>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/lumiumseeds", <mysticalagriculture:lumium_seeds>, 500, 300, [<ore:ingotLumium>, <ore:dustAstralStarmetal>, <ore:ingotLumium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotLumium>, <ore:dustAstralStarmetal>, <ore:ingotLumium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/fluxedelectrumseeds", <mysticalagriculture:fluxed_electrum_seeds>, 500, 300, [<ore:ingotElectrumFlux>, <ore:dustAstralStarmetal>, <ore:ingotElectrumFlux>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotElectrumFlux>, <ore:dustAstralStarmetal>, <ore:ingotElectrumFlux>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/hopseeds", <mysticalagriculture:hop_graphite_seeds>, 500, 300, [<ore:ingotHOPGraphite>, <ore:dustAstralStarmetal>, <ore:ingotHOPGraphite>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotHOPGraphite>, <ore:dustAstralStarmetal>, <ore:ingotHOPGraphite>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/cobaltseeds", <mysticalagriculture:cobalt_seeds>, 500, 300, [<ore:ingotCobalt>, <ore:dustAstralStarmetal>, <ore:ingotCobalt>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotCobalt>, <ore:dustAstralStarmetal>, <ore:ingotCobalt>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/soulariumseeds", <mysticalagriculture:soularium_seeds>, 500, 300, [<ore:ingotSoularium>, <ore:dustAstralStarmetal>, <ore:ingotSoularium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotSoularium>, <ore:dustAstralStarmetal>, <ore:ingotSoularium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/darksteelseeds", <mysticalagriculture:dark_steel_seeds>, 500, 300, [<ore:ingotDarkSteel>, <ore:dustAstralStarmetal>, <ore:ingotDarkSteel>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotDarkSteel>, <ore:dustAstralStarmetal>, <ore:ingotDarkSteel>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/pulsatingironseeds", <mysticalagriculture:pulsating_iron_seeds>, 500, 300, [<ore:ingotPulsatingIron>, <ore:dustAstralStarmetal>, <ore:ingotPulsatingIron>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotPulsatingIron>, <ore:dustAstralStarmetal>, <ore:ingotPulsatingIron>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/energeticalloyseeds", <mysticalagriculture:energetic_alloy_seeds>, 500, 300, [<ore:ingotEnergeticAlloy>, <ore:dustAstralStarmetal>, <ore:ingotEnergeticAlloy>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotEnergeticAlloy>, <ore:dustAstralStarmetal>, <ore:ingotEnergeticAlloy>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/elementiumseeds", <mysticalagriculture:elementium_seeds>, 500, 300, [<ore:ingotElvenElementium>, <ore:dustAstralStarmetal>, <ore:ingotElvenElementium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotElvenElementium>, <ore:dustAstralStarmetal>, <ore:ingotElvenElementium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/dawnstoneseeds", <mysticalagriculture:dawnstone_seeds>, 500, 300, [<ore:ingotDawnstone>, <ore:dustAstralStarmetal>, <ore:ingotDawnstone>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotDawnstone>, <ore:dustAstralStarmetal>, <ore:ingotDawnstone>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/osmiumseeds", <mysticalagriculture:osmium_seeds>, 500, 300, [<ore:ingotOsmium>, <ore:dustAstralStarmetal>, <ore:ingotOsmium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotOsmium>, <ore:dustAstralStarmetal>, <ore:ingotOsmium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/glowstoneingotseeds", <mysticalagriculture:glowstone_ingot_seeds>, 500, 300, [<ore:ingotRefinedGlowstone>, <ore:dustAstralStarmetal>, <ore:ingotRefinedGlowstone>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotRefinedGlowstone>, <ore:dustAstralStarmetal>, <ore:ingotRefinedGlowstone>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/knightmetalseeds", <mysticalagriculture:knightmetal_seeds>, 500, 300, [<ore:ingotKnightmetal>, <ore:dustAstralStarmetal>, <ore:ingotKnightmetal>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotKnightmetal>, <ore:dustAstralStarmetal>, <ore:ingotKnightmetal>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/fieryseeds", <mysticalagriculture:fiery_ingot_seeds>, 500, 300, [<ore:ingotFiery>, <ore:dustAstralStarmetal>, <ore:ingotFiery>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotFiery>, <ore:dustAstralStarmetal>, <ore:ingotFiery>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/meteroicironseeds", <mysticalagriculture:meteoric_iron_seeds>, 500, 300, [<ore:ingotMeteoricIron>, <ore:dustAstralStarmetal>, <ore:ingotMeteoricIron>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotMeteoricIron>, <ore:dustAstralStarmetal>, <ore:ingotMeteoricIron>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/abyssalniteseeds", <mysticalagriculture:abyssalnite_seeds>, 500, 300, [<ore:ingotAbyssalnite>, <ore:dustAstralStarmetal>, <ore:ingotAbyssalnite>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotAbyssalnite>, <ore:dustAstralStarmetal>, <ore:ingotAbyssalnite>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/thoriumseeds", <mysticalagriculture:thorium_seeds>, 500, 300, [<ore:ingotThorium>, <ore:dustAstralStarmetal>, <ore:ingotThorium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotThorium>, <ore:dustAstralStarmetal>, <ore:ingotThorium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/boronseeds", <mysticalagriculture:boron_seeds>, 500, 300, [<ore:ingotBoron>, <ore:dustAstralStarmetal>, <ore:ingotBoron>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotBoron>, <ore:dustAstralStarmetal>, <ore:ingotBoron>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/lithiumseeds", <mysticalagriculture:lithium_seeds>, 500, 300, [<ore:ingotLithium>, <ore:dustAstralStarmetal>, <ore:ingotLithium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotLithium>, <ore:dustAstralStarmetal>, <ore:ingotLithium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/magnesiumseeds", <mysticalagriculture:magnesium_seeds>, 500, 300, [<ore:ingotMagnesium>, <ore:dustAstralStarmetal>, <ore:ingotMagnesium>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotMagnesium>, <ore:dustAstralStarmetal>, <ore:ingotMagnesium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/starmetalseeds", <mysticalagriculture:starmetal_seeds>, 500, 300, [<ore:ingotAstralStarmetal>, <ore:dustAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:dustAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/jadeseeds", <mysticalagriculture:jade_seeds>, 500, 300, [<ore:gemJade>, <ore:dustAstralStarmetal>, <ore:gemJade>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:gemJade>, <ore:dustAstralStarmetal>, <ore:gemJade>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/compressedironseeds", <mysticalagriculture:compressed_iron_seeds>, 500, 300, [<ore:ingotIronCompressed>, <ore:dustAstralStarmetal>, <ore:ingotIronCompressed>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:ingotIronCompressed>, <ore:dustAstralStarmetal>, <ore:ingotIronCompressed>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);
mods.astralsorcery.Altar.addAttunementAltarRecipe("po3:shaped/internal/altar/fluixseeds", <mysticalagriculture:fluix_seeds>, 500, 300, [<ore:crystalFluix>, <ore:dustAstralStarmetal>, <ore:crystalFluix>, <ore:dustAstralStarmetal>, <mysticalagriculture:crafting:20>, <ore:dustAstralStarmetal>, <ore:crystalFluix>, <ore:dustAstralStarmetal>, <ore:crystalFluix>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>, <ore:essenceSuperium>]);