#packmode kappa
//9x9 table
recipes.remove(<extendedcrafting:table_ultimate>);

mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:table_ultimate>, [[<extendedcrafting:material:17>, <extendedcrafting:material:17>, <extendedcrafting:material:17>, <extendedcrafting:material:11>, <extendedcrafting:material:17>, <extendedcrafting:material:17>, <extendedcrafting:material:17>], [<extendedcrafting:material:17>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotVibrantAlloy>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <extendedcrafting:material:17>], [<extendedcrafting:material:17>, <ore:ingotAstralStarmetal>, <ore:gemGreenDiamond>, <actuallyadditions:item_crystal_empowered:4>, <ore:gemGreenDiamond>, <ore:ingotAstralStarmetal>, <extendedcrafting:material:17>], [<ore:ingotVibrantAlloy>, <ore:ingotVibrantAlloy>, <actuallyadditions:item_crystal_empowered:4>, <bloodmagic:decorative_brick:2>, <actuallyadditions:item_crystal_empowered:4>, <ore:ingotVibrantAlloy>, <ore:ingotVibrantAlloy>], [<extendedcrafting:material:17>, <ore:ingotAstralStarmetal>, <ore:gemGreenDiamond>, <actuallyadditions:item_crystal_empowered:4>, <ore:gemGreenDiamond>, <ore:ingotAstralStarmetal>, <extendedcrafting:material:17>], [<extendedcrafting:material:17>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotVibrantAlloy>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <extendedcrafting:material:17>], [<extendedcrafting:material:17>, <extendedcrafting:material:17>, <extendedcrafting:material:17>, <ore:ingotVibrantAlloy>, <extendedcrafting:material:17>, <extendedcrafting:material:17>, <extendedcrafting:material:17>]]);

//crystaltine ingot
mods.extendedcrafting.TableCrafting.remove(<extendedcrafting:material:24>);

mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:material:24>, [[<ore:manaDiamond>, <embers:seed_aluminum>, <contenttweaker:neutral_steel_6>, <tombstone:crafting_ingredient:2>, <contenttweaker:neutral_steel_6>, <embers:seed_aluminum>, <ore:manaDiamond>], [<tombstone:crafting_ingredient:2>, <ore:ingotCrystallineAlloy>, <embers:seed_aluminum>, <lordcraft:crystal_basic_lightning:1>, <embers:seed_aluminum>, <ore:ingotCrystallineAlloy>, <tombstone:crafting_ingredient:2>], [<ore:crystalOsmium>, <ore:crystalPureFluix>, <ore:ingotCrystallineAlloy>, <ore:ingotCrystallineAlloy>, <ore:ingotCrystallineAlloy>, <ore:crystalPureFluix>, <ore:crystalOsmium>], [<tombstone:crafting_ingredient:2>, <ore:ingotCrystallineAlloy>, <embers:seed_aluminum>, <lordcraft:crystal_basic_lightning:1>, <embers:seed_aluminum>, <ore:ingotCrystallineAlloy>, <tombstone:crafting_ingredient:2>], [<ore:manaDiamond>, <embers:seed_aluminum>, <contenttweaker:neutral_steel_6>, <tombstone:crafting_ingredient:2>, <contenttweaker:neutral_steel_6>, <embers:seed_aluminum>, <ore:manaDiamond>], [null, null, null, null, null, null, null], [null, null, null, null, null, null, null]]);

//quantum compressor
recipes.remove(<extendedcrafting:compressor>);

mods.extendedcrafting.TableCrafting.addShaped(0, <extendedcrafting:compressor>, [[<ore:ingotBlackIron>, <ore:plateTungsten>, <extendedcrafting:material:10>, <extendedcrafting:material:10>, <extendedcrafting:material:10>, <ore:plateTungsten>, <ore:ingotBlackIron>], [<ore:plateTungsten>, <ore:plateTungsten>, <ore:enderDragonScale>, <contenttweaker:neutral_steel_8>, <ore:enderDragonScale>, <ore:plateTungsten>, <ore:plateTungsten>], [<extendedcrafting:material:16>, <ore:enderDragonScale>, <galacticraftcore:machine2>, <pneumaticcraft:advanced_air_compressor>, <galacticraftcore:machine2>, <ore:enderDragonScale>, <extendedcrafting:material:16>], [<extendedcrafting:material:16>, <contenttweaker:neutral_steel_8>, <ae2stuff:inscriber>, <extendedcrafting:frame>, <ae2stuff:inscriber>, <contenttweaker:neutral_steel_8>, <extendedcrafting:material:16>], [<extendedcrafting:material:16>, <ore:enderDragonScale>, <galacticraftcore:machine2>, <ae2stuff:inscriber>, <galacticraftcore:machine2>, <ore:enderDragonScale>, <extendedcrafting:material:16>], [<ore:plateTungsten>, <ore:plateTungsten>, <ore:enderDragonScale>, <contenttweaker:neutral_steel_8>, <ore:enderDragonScale>, <ore:plateTungsten>, <ore:plateTungsten>], [<ore:ingotBlackIron>, <ore:plateTungsten>, <extendedcrafting:material:2>, <extendedcrafting:material:2>, <extendedcrafting:material:2>, <ore:plateTungsten>, <ore:ingotBlackIron>]]);

//creative modifier
mods.extendedcrafting.TableCrafting.addShaped(0, <tconstruct:materials:50>, [[<extendedcrafting:trimmed:3>, <ore:ingotAlubrass>, <contenttweaker:neutral_steel_7>, <tconstruct:materials:12>, <contenttweaker:neutral_steel_7>, <ore:ingotAlubrass>, <extendedcrafting:trimmed:3>], [<ore:ingotAlubrass>, <ore:ingotKnightslime>, <ore:ingotCrystaltine>, <ore:ingotBlackIron>, <ore:ingotCrystaltine>, <ore:ingotKnightslime>, <ore:ingotAlubrass>], [<ore:ingotThorium>, <contenttweaker:neutral_steel_7>, <ore:ingotKnightslime>, <ore:ingotCrystaltine>, <ore:ingotKnightslime>, <contenttweaker:neutral_steel_7>, <ore:ingotThorium>], [<tconstruct:materials:13>, <contenttweaker:neutral_steel_7>, <mysticalagradditions:stuff:69>, <tconstruct:materials:16>, <mysticalagradditions:stuff:69>, <contenttweaker:neutral_steel_7>, <tconstruct:materials:13>], [<ore:ingotThorium>, <contenttweaker:neutral_steel_7>, <ore:ingotManyullyn>, <mysticalagradditions:stuff:69>, <ore:ingotManyullyn>, <contenttweaker:neutral_steel_7>, <ore:ingotThorium>], [<ore:ingotAlubrass>, <contenttweaker:neutral_steel_7>, <forge:bucketfilled>.withTag({FluidName:"lifeessence",Amount:1000}), <extendedcrafting:frame>, <forge:bucketfilled>.withTag({FluidName:"lifeessence",Amount:1000}), <contenttweaker:neutral_steel_7>, <ore:ingotAlubrass>], [<extendedcrafting:trimmed:3>, <ore:ingotAlubrass>, <contenttweaker:neutral_steel_7>, <tconstruct:materials:12>, <contenttweaker:neutral_steel_7>, <ore:ingotAlubrass>, <extendedcrafting:trimmed:3>]]);

//creative cobble generator
mods.extendedcrafting.TableCrafting.addShaped(0, <compacter:cobbler>, [[<extrautils2:machine>.withTag({Type:"extrautils2:furnace"}), <magneticraft:brick_furnace>, <ceramics:unfired_clay:5>, <tp:emerald_cobblegen_block>, <ceramics:unfired_clay:5>, <magneticraft:brick_furnace>, <extrautils2:machine>.withTag({Type:"extrautils2:furnace"})], [<mysticalagriculture:ultimate_furnace>, <mysticalagradditions:stuff:69>, <ore:ingotCrystaltine>, <pneumaticcraft:network_component:3>, <ore:ingotCrystaltine>, <mysticalagradditions:stuff:69>, <mysticalagriculture:ultimate_furnace>], [<ore:compressed6xNetherrack>, <ore:ingotCrystaltine>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <ore:ingotCrystaltine>, <ore:compressed6xNetherrack>], [<nuclearcraft:cobblestone_generator_dense>, <overloaded:compressed_end_stone:7>, <tp:lava_infused_stone>, <ore:compressed8xCobblestone>, <tp:lava_infused_stone>, <overloaded:compressed_end_stone:7>, <nuclearcraft:cobblestone_generator_dense>], [<ore:compressed6xNetherrack>, <ore:ingotCrystaltine>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <tp:lava_infused_stone>, <ore:ingotCrystaltine>, <ore:compressed6xNetherrack>], [<furnaceoverhaul:zenith_furnace>, <mysticalagradditions:stuff:69>, <ore:ingotCrystaltine>, <pneumaticcraft:network_component:3>, <ore:ingotCrystaltine>, <mysticalagradditions:stuff:69>, <furnaceoverhaul:zenith_furnace>], [<tp:blaze_cobblegen_block>, <tp:diamond_cobblegen_block>, <tp:iron_cobblegen_block>, <tp:cobblegen_block>, <tp:iron_cobblegen_block>, <tp:diamond_cobblegen_block>, <tp:blaze_cobblegen_block>]]);