
#Tweaks
[tweaks]
	#Want a way to clear text in signs?
	enableSignEditing = false
	#Want the fire arrows to set fire on block it landed?
	arrowsSetBlockOnFire = false
	#Want to shear nametag of named entities?
	shearOffNameTag = true
	#Want baby zombies to burn by the light of the day?
	babyZombieBurnInDaylight = true
	#Want creeper's to burn in daylight?
	creeperBurnInDaylight = false
	#Want TNT to ignite when next to lava or magma block?
	tntIgnition = true
	#Want hoe to act like a sickle?
	hoeActsAsSickle = false
	#Want the ability to move spawners with silk touch?
	enableSilkSpawner = false
	#Want an way to swap armor with armor stand?
	enableArmorStandSwapping = true
	#Do you want to neglect fall damage and get water spilled when you fall on a wet sponge?
	squishySponge = true
	#Want command block to appear in redstone tab?
	commandBlockInRedstone = true
	#Want dragon egg to appear in decorations tab?
	dragonEggInDecorations = true
	#Want to shift click item frame to rotate in the reverse direction?
	itemFrameRotateBackwards = true
	#Want to disable shift in GUI due to potions?
	disablePotionShift = false

