#packmode normal

//creative ember block
mods.extendedcrafting.CombinationCrafting.addRecipe(<embers:creative_ember_source>, 250000, <extendedcrafting:material:32>, [<contenttweaker:neutral_steel_3>, <contenttweaker:neutral_steel_3>, <contenttweaker:neutral_steel_3>, <contenttweaker:neutral_steel_3>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:plateDawnstone>, <ore:plateDawnstone>, <ore:plateDawnstone>, <ore:plateDawnstone>, <ore:plateDawnstone>, <ore:plateDawnstone>, <ore:plateDawnstone>, <ore:plateDawnstone>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <embers:ember_cluster>,  <lordcraft:tile:5>, <lordcraft:tile:13>, <lordcraft:tile:2>, <lordcraft:tile:5>, <lordcraft:tile:18>]);

//everlasting guilty pool
mods.extendedcrafting.CombinationCrafting.addRecipe(<botania:pool:1>, 500000, <botania:pool:3>, [<astralsorcery:itemcraftingcomponent:4>, <astralsorcery:itemcraftingcomponent:4>, <astralsorcery:itemcraftingcomponent:4>, <astralsorcery:itemcraftingcomponent:4>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotInfinity>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:ingotAstralStarmetal>, <ore:gaiaIngot>, <ore:gaiaIngot>, <ore:gaiaIngot>, <ore:gaiaIngot>, <ore:ingotElvenElementium>, <ore:ingotElvenElementium>, <ore:ingotElvenElementium>, <ore:ingotElvenElementium>, <ore:ingotTerrasteel>, <ore:ingotTerrasteel>, <ore:ingotTerrasteel>, <ore:ingotTerrasteel>, <ore:elvenPixieDust>, <ore:elvenPixieDust>, <ore:elvenPixieDust>, <ore:elvenPixieDust>, <contenttweaker:neutral_steel_11>]);

//Creative Chest
mods.extendedcrafting.CombinationCrafting.addRecipe(<extrautils2:creativechest>, 10000000, <draconicevolution:draconium_chest>, [<extendedcrafting:material:13>, <extendedcrafting:material:13>, <extendedcrafting:material:13>, <extendedcrafting:material:13>, <extendedcrafting:material:13>, <extendedcrafting:material:13>, <extendedcrafting:material:13>, <extendedcrafting:material:13>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:chaos_block>, <contenttweaker:neutral_steel_11>, <contenttweaker:neutral_steel_11>, <contenttweaker:neutral_steel_11>, <contenttweaker:neutral_steel_11>]);

