#packmode titan
mods.botania.RuneAltar.removeRecipe(<botania:rune:*>);
//fire
mods.botania.RuneAltar.addRecipe(<botania:rune:1> * 2,[<ore:powderMana>, <ore:ingotManasteel>, <ore:ingotBrickNether>, <ore:gunpowder>, <ore:cropNetherWart>, <bloodmagic:slate:0>], 5200);
//earth
mods.botania.RuneAltar.addRecipe(<botania:rune:2> * 2,[<ore:powderMana>, <ore:ingotManasteel>, <ore:stone>, <ore:blockCoal>, <ore:listAllmushroom>, <bloodmagic:slate:0>], 5200);
//air
mods.botania.RuneAltar.addRecipe(<botania:rune:3> * 2, [<ore:powderMana>, <ore:ingotManasteel>, <ore:carpet>, <ore:feather>, <ore:string>, <bloodmagic:slate:0>], 5200);
//water
mods.botania.RuneAltar.addRecipe(<botania:rune> * 2, [<ore:powderMana>, <ore:ingotManasteel>, <minecraft:dye:15>, <ore:sugarcane>, <minecraft:fishing_rod>, <bloodmagic:slate:0>], 5200);
//mana
mods.botania.RuneAltar.addRecipe(<botania:rune:8>, [<ore:ingotManasteel>, <ore:ingotManasteel>, <ore:ingotManasteel>, <ore:ingotManasteel>, <ore:ingotManasteel>, <ore:manaPearl>, <bloodmagic:slate:0>], 8000);
//summer
mods.botania.RuneAltar.addRecipe(<botania:rune:5>, [<ore:runeEarthB>, <ore:runeAirB>, <minecraft:sand>, <minecraft:sand>, <ore:slimeball>, <minecraft:melon>, <bloodmagic:slate:0>], 8000);
//autumn
mods.botania.RuneAltar.addRecipe(<botania:rune:6>, [<ore:runeFireB>, <ore:runeAirB>, <ore:treeLeaves>, <ore:treeLeaves>, <ore:treeLeaves>, <minecraft:spider_eye>, <bloodmagic:slate:0>], 8000);
//winter
mods.botania.RuneAltar.addRecipe(<botania:rune:7>, [<ore:runeWaterB>, <ore:runeEarthB>, <minecraft:snow>, <minecraft:snow>, <ore:blockWool>, <minecraft:cake>, <bloodmagic:slate:0>], 8000);
//spring
mods.botania.RuneAltar.addRecipe(<botania:rune:4>, [<ore:runeWaterB>, <ore:runeFireB>, <ore:treeSapling>, <ore:treeSapling>, <ore:treeSapling>, <ore:cropWheat>, <bloodmagic:slate:0>], 8000);
//lust
mods.botania.RuneAltar.addRecipe(<botania:rune:9>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeSummerB>, <ore:runeAirB>, <bloodmagic:slate:0>], 12000);
//gluttony
mods.botania.RuneAltar.addRecipe(<botania:rune:10>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeWinterB>, <ore:runeFireB>, <bloodmagic:slate:0>], 12000);
//greed
mods.botania.RuneAltar.addRecipe(<botania:rune:11>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeSpringB>, <ore:runeWaterB>, <bloodmagic:slate:0>], 12000);
//sloth
mods.botania.RuneAltar.addRecipe(<botania:rune:12>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeAutumnB>, <ore:runeAirB>, <bloodmagic:slate:0>], 12000);
//wrath
mods.botania.RuneAltar.addRecipe(<botania:rune:13>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeWinterB>, <ore:runeEarthB>, <bloodmagic:slate:0>], 12000);
//envy
mods.botania.RuneAltar.addRecipe(<botania:rune:14>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeWinterB>, <ore:runeWaterB>, <bloodmagic:slate:0>], 12000);
//pride
mods.botania.RuneAltar.addRecipe(<botania:rune:15>, [<ore:manaDiamond>, <ore:manaDiamond>, <ore:runeSummerB>, <ore:runeFireB>, <bloodmagic:slate:0>], 12000);
//Seeds
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:iron_seeds>, [<ore:manaDiamond>, <ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:nether_quartz_seeds>, [<ore:manaDiamond>, <ore:gemQuartz>, <ore:gemQuartz>, <ore:gemQuartz>, <ore:gemQuartz>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:glowstone_seeds>, [<ore:manaDiamond>, <ore:blockGlowstone>, <ore:blockGlowstone>, <ore:blockGlowstone>, <ore:blockGlowstone>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:redstone_seeds>, [<ore:manaDiamond>, <ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:obsidian_seeds>, [<ore:manaDiamond>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:skeleton_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:12>, <mysticalagriculture:chunk:12>, <mysticalagriculture:chunk:12>, <mysticalagriculture:chunk:12>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:creeper_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:13>, <mysticalagriculture:chunk:13>, <mysticalagriculture:chunk:13>, <mysticalagriculture:chunk:13>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:spider_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:14>, <mysticalagriculture:chunk:14>, <mysticalagriculture:chunk:14>, <mysticalagriculture:chunk:14>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:rabbit_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:15>, <mysticalagriculture:chunk:15>, <mysticalagriculture:chunk:15>, <mysticalagriculture:chunk:15>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:guardian_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:16>, <mysticalagriculture:chunk:16>, <mysticalagriculture:chunk:16>, <mysticalagriculture:chunk:16>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:saltpeter_seeds>, [<ore:manaDiamond>, <ore:dustSaltpeter>, <ore:dustSaltpeter>, <ore:dustSaltpeter>, <ore:dustSaltpeter>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:tin_seeds>, [<ore:manaDiamond>, <ore:ingotTin>, <ore:ingotTin>, <ore:ingotTin>, <ore:ingotTin>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:bronze_seeds>, [<ore:manaDiamond>, <ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:silver_seeds>, [<ore:manaDiamond>, <ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>, <ore:ingotSilver>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:lead_seeds>, [<ore:manaDiamond>, <ore:ingotLead>, <ore:ingotLead>, <ore:ingotLead>, <ore:ingotLead>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:graphite_seeds>, [<ore:manaDiamond>, <ore:ingotGraphite>, <ore:ingotGraphite>, <ore:ingotGraphite>, <ore:ingotGraphite>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:blizz_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:21>, <mysticalagriculture:chunk:21>, <mysticalagriculture:chunk:21>, <mysticalagriculture:chunk:21>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:blitz_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:22>, <mysticalagriculture:chunk:22>, <mysticalagriculture:chunk:22>, <mysticalagriculture:chunk:22>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:basalz_seeds>, [<ore:manaDiamond>, <mysticalagriculture:chunk:23>, <mysticalagriculture:chunk:23>, <mysticalagriculture:chunk:23>, <mysticalagriculture:chunk:23>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:knightslime_seeds>, [<ore:manaDiamond>, <ore:ingotKnightslime>, <ore:ingotKnightslime>, <ore:ingotKnightslime>, <ore:ingotKnightslime>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:ardite_seeds>, [<ore:manaDiamond>, <ore:ingotArdite>, <ore:ingotArdite>, <ore:ingotArdite>, <ore:ingotArdite>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:electrical_steel_seeds>, [<ore:manaDiamond>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:ingotElectricalSteel>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:redstone_alloy_seeds>, [<ore:manaDiamond>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <ore:ingotRedstoneAlloy>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:conductive_iron_seeds>, [<ore:manaDiamond>, <ore:ingotConductiveIron>, <ore:ingotConductiveIron>, <ore:ingotConductiveIron>, <ore:ingotConductiveIron>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:manasteel_seeds>, [<ore:manaDiamond>, <ore:ingotManasteel>, <ore:ingotManasteel>, <ore:ingotManasteel>, <ore:ingotManasteel>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:electrotine_seeds>, [<ore:manaDiamond>, <ore:dustElectrotine>, <ore:dustElectrotine>, <ore:dustElectrotine>, <ore:dustElectrotine>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:steeleaf_seeds>, [<ore:manaDiamond>, <ore:ingotSteeleaf>, <ore:ingotSteeleaf>, <ore:ingotSteeleaf>, <ore:ingotSteeleaf>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:ironwood_seeds>, [<ore:manaDiamond>, <ore:ingotIronwood>, <ore:ingotIronwood>, <ore:ingotIronwood>, <ore:ingotIronwood>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:coralium_seeds>, [<ore:manaDiamond>, <abyssalcraft:ccluster9>, <abyssalcraft:ccluster9>, <abyssalcraft:ccluster9>, <abyssalcraft:ccluster9>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:black_quartz_seeds>, [<ore:manaDiamond>, <ore:gemQuartzBlack>, <ore:gemQuartzBlack>, <ore:gemQuartzBlack>, <ore:gemQuartzBlack>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:aquamarine_seeds>, [<ore:manaDiamond>, <ore:gemAquamarine>, <ore:gemAquamarine>, <ore:gemAquamarine>, <ore:gemAquamarine>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:ender_biotite_seeds>, [<ore:manaDiamond>, <ore:gemEnderBiotite>, <ore:gemEnderBiotite>, <ore:gemEnderBiotite>, <ore:gemEnderBiotite>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:sky_stone_seeds>, [<ore:manaDiamond>, <appliedenergistics2:sky_stone_block>, <appliedenergistics2:sky_stone_block>, <appliedenergistics2:sky_stone_block>, <appliedenergistics2:sky_stone_block>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);
mods.botania.RuneAltar.addRecipe(<mysticalagriculture:certus_quartz_seeds>, [<ore:manaDiamond>, <ore:crystalCertusQuartz>, <ore:crystalCertusQuartz>, <ore:crystalCertusQuartz>, <ore:crystalCertusQuartz>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <ore:essenceIntermedium>, <mysticalagriculture:crafting:19>], 10000);