#priority 5
#packmode normal titan kappa
//Don't touch me!
//#Remove
recipes.remove(<lootbags:loot_storage>);
recipes.remove(<erebus:glider_chestplate>);
recipes.remove(<erebus:glider_chestplate_powered>);
recipes.remove(<extraplanets:ultimate_battery:100>);
recipes.remove(<industrialforegoing:mob_relocator>);
recipes.remove(<industrialforegoing:crop_recolector>);
recipes.remove(<industrialforegoing:mob_slaughter_factory>);
recipes.remove(<industrialforegoing:laser_drill>);
recipes.remove(<industrialforegoing:laser_base>);
recipes.remove(<industrialforegoing:tree_fluid_extractor>);
recipes.remove(<industrialforegoing:latex_processing_unit>);
recipes.remove(<extrautils2:grocket:6>);
recipes.remove(<extrautils2:grocket:2>);
recipes.remove(<extrautils2:grocket:0>);
recipes.remove(<extrautils2:pipe>);
recipes.remove(<openblocks:scaffolding>);
recipes.remove(<extrautils2:filterfluids>);
recipes.remove(<extrautils2:filter>);
recipes.remove(<extrautils2:grocket:1>);
recipes.remove(<extrautils2:grocket:5>);
recipes.remove(<extrautils2:flattransfernode:1>);
recipes.remove(<extrautils2:flattransfernode:0>);
recipes.remove(<tcomplement:knightslime_boots>);
recipes.remove(<tcomplement:knightslime_leggings>);
recipes.remove(<tcomplement:knightslime_chestplate>);
recipes.remove(<tcomplement:knightslime_helmet>);
recipes.remove(<mekanismtools:lapislazulichestplate>);
recipes.remove(<mekanismtools:lapislazulileggings>);
recipes.remove(<mekanismtools:lapislazuliboots>);
recipes.remove(<mekanismtools:lapislazulihelmet>);
recipes.remove(<tcomplement:steel_boots>);
recipes.remove(<tcomplement:steel_leggings>);
recipes.remove(<tcomplement:steel_chestplate>);
recipes.remove(<tcomplement:steel_helmet>);
recipes.remove(<immersiveengineering:steel_armor_feet>);
recipes.remove(<immersiveengineering:steel_armor_legs>);
recipes.remove(<immersiveengineering:steel_armor_chest>);
recipes.remove(<immersiveengineering:steel_armor_head>);
recipes.remove(<astralsorcery:itemjournal>);
recipes.remove(<extrautils2:machine>.withTag({Type: "extrautils2:generator_slime"}));
recipes.remove(<extraplanets:tungsten_boots>);
recipes.remove(<extraplanets:tungsten_legings>);
recipes.remove(<extraplanets:tungsten_chest>);
recipes.remove(<extraplanets:tungsten_helmet>);
recipes.remove(<extracells:terminal.gas.wireless>);
recipes.remove(<extracells:terminal.universal.wireless>);
recipes.remove(<extracells:terminal.fluid.wireless>);
recipes.remove(<thermalsolars:itemenderexcavator>);
recipes.remove(<xreliquary:rending_gale>);
recipes.remove(<avaritia:resource:1>);
recipes.remove(<thermalsolars:itemlunarexcavator>);
recipes.remove(<thermalsolars:itemenderhammer>);
recipes.remove(<thermalsolars:itemlunarhammer>);
recipes.remove(<thermalsolars:itemenderhoe>);
recipes.remove(<thermalsolars:itemlunarhoe>);
recipes.remove(<thermalsolars:itemenderaxe>);
recipes.remove(<thermalsolars:itemlunaraxe>);
recipes.remove(<thermalsolars:itemenderspade>);
recipes.remove(<thermalsolars:itemlunarspade>);
recipes.remove(<thermalsolars:itemendersword>);
recipes.remove(<thermalsolars:itemlunarsword>);
recipes.remove(<thermalsolars:itemenderpickaxe>);
recipes.remove(<thermalsolars:itemlunarpickaxe>);
recipes.remove(<thermalsolars:itemtitaniumexcavator>);
recipes.remove(<thermalsolars:itemtitaniumhammer>);
recipes.remove(<thermalsolars:itemtitaniummultitool>);
recipes.remove(<thermalsolars:itemtitaniumhoe>);
recipes.remove(<thermalsolars:itemtitaniumaxe>);
recipes.remove(<thermalsolars:itemtitaniumspade>);
recipes.remove(<thermalsolars:itemtitaniumsword>);
recipes.remove(<thermalsolars:itemtitaniumpickaxe>);
recipes.removeShapeless(<harvestcraft:barleyseeditem>, [ <harvestcraft:barleyitem>]);
recipes.removeShapeless(<minecraft:string> * 9, [<erebus:silk>]);
recipes.remove(<actuallyadditions:block_fluid_placer>);
recipes.remove(<minecraft:fire_charge> * 3);
recipes.remove(<enderio:item_capacitor_silver>);
recipes.remove(<enderio:item_basic_capacitor>);
recipes.remove(<extraplanets:pluto:7>);
recipes.remove(<extrautils2:opinium>);
recipes.remove(<tp:watering_can_upgrade>);
recipes.remove(<exnihilocreatio:crook_granite>);
recipes.remove(<exnihilocreatio:crook_diorite>);
recipes.remove(<exnihilocreatio:crook_andesite>);
recipes.remove(<exnihilocreatio:crook_stone>);
recipes.remove(<simplyjetpacks:itemfluxpack>);
recipes.remove(<actuallyadditions:block_placer>);
recipes.remove(<equivalentintegrations:soulbound_talisman>);
recipes.remove(<mysticalagriculture:master_infusion_crystal>);
recipes.remove(<extraplanets:tier8_items:1>);
recipes.remove(<erebus:wand_of_animation>);
recipes.remove(<quark:reed_block>);
recipes.remove(<mekanism:basicblock2:7> * 4);
recipes.remove(<botania:fertilizer>);
recipes.remove(<yabba:antibarrel>);
recipes.remove(<appliedenergistics2:material:40>);
recipes.remove(<magneticraft:small_tank>);
recipes.remove(<enderio:item_material:9>);
recipes.remove(<thermalfoundation:storage:3>);
recipes.remove(<embers:stone_edge>);
recipes.remove(<extraplanets:tools:2>);
recipes.remove(<immersiveengineering:tool>);
recipes.remove(<projectred-expansion:jetpack>);
recipes.remove(<enderio:item_material:9>);
recipes.remove(<blockcraftery:editable_block>);
recipes.remove(<mysticalagriculture:crafting:50>);
recipes.remove(<portality:frame>);
recipes.remove(<portality:controller>);
recipes.remove(<projecte:item.pe_tome>);
recipes.remove(<projecte:item.pe_repair_talisman>);
recipes.remove(<projecte:item.pe_transmutation_tablet>);
recipes.remove(<projecte:condenser_mk2>);
recipes.remove(<projecte:condenser_mk1>);
recipes.remove(<projecte:transmutation_table>);
recipes.remove(<projecte:item.pe_philosophers_stone>);
recipes.remove(<exnihilocreatio:block_end_cake>);
recipes.remove(<bigreactors:blockyellorium>);
recipes.remove(<projectred-expansion:machine2:10>);
recipes.remove(<projectred-expansion:machine2:11>);
recipes.remove(<erebus:silk>);
recipes.remove(<randomthings:fertilizeddirt>);
recipes.remove(<chancecubes:scanner>);
recipes.remove(<chancecubes:chance_pendant_tier3>);
recipes.remove(<chancecubes:chance_pendant_tier2>);
recipes.remove(<chancecubes:chance_pendant_tier1>);
recipes.remove(<chancecubes:silk_touch_pendant>);
recipes.remove(<abyssalcraft:cobbleu>);
recipes.remove(<abyssalcraft:ironu>);
recipes.remove(<abyssalcraft:goldu>);
recipes.remove(<abyssalcraft:diamondu>);
recipes.remove(<abyssalcraft:abyssalniteu>);
recipes.remove(<abyssalcraft:coraliumu>);
recipes.remove(<actuallyadditions:item_wings_of_the_bats>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:8>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:7>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:6>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:5>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:4>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:3>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:2>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:1>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:0>);
recipes.remove(<actuallyadditions:item_potion_ring_advanced:9>);
recipes.remove(<actuallyadditions:item_potion_ring:8>);
recipes.remove(<actuallyadditions:item_potion_ring:7>);
recipes.remove(<actuallyadditions:item_potion_ring:6>);
recipes.remove(<actuallyadditions:item_potion_ring:5>);
recipes.remove(<actuallyadditions:item_potion_ring:4>);
recipes.remove(<actuallyadditions:item_potion_ring:3>);
recipes.remove(<actuallyadditions:item_potion_ring:2>);
recipes.remove(<actuallyadditions:item_potion_ring:1>);
recipes.remove(<actuallyadditions:item_potion_ring:0>);
recipes.remove(<actuallyadditions:item_potion_ring:9>);
recipes.remove(<witherskelefix:blade>);
recipes.remove(<witherskelefix:blade2>);
recipes.remove(<tp:growth_upgrade_two>);
recipes.remove(<tp:growth_upgrade>);
recipes.remove(<tp:growth_block>);
recipes.remove(<magneticraft:light_plates:6>);
recipes.remove(<magneticraft:light_plates:5>);
recipes.remove(<magneticraft:light_plates:3>);
recipes.remove(<magneticraft:light_plates:2>);
recipes.remove(<magneticraft:light_plates:1>);
recipes.remove(<magneticraft:light_plates>);
recipes.remove(<bloodmagic:soul_forge>);
recipes.remove(<bloodmagic:soul_snare>);
recipes.remove(<woot:layout>);
recipes.remove(<woot:structure:5>);
recipes.remove(<woot:structure:1>);
recipes.remove(<woot:structure>);
recipes.remove(<immersiveengineering:metal_device1:13>);
recipes.remove(<actuallyadditions:item_misc:19>);
recipes.remove(<harvestcraft:market>);
recipes.remove(<mysticalagriculture:watering_can:4>);
recipes.remove(<mysticalagriculture:watering_can:3>);
recipes.remove(<mysticalagriculture:watering_can:2>);
recipes.remove(<mysticalagriculture:watering_can:1>);
recipes.remove(<tp:watering_can>);
recipes.remove(<rftools:machine_frame>);
recipes.remove(<armorplus:workbench>);
recipes.remove(<draconicevolution:wyvern_boots>);
recipes.remove(<draconicevolution:wyvern_legs>);
recipes.remove(<draconicevolution:wyvern_chest>);
recipes.remove(<draconicevolution:wyvern_helm>);
recipes.remove(<projecte:collector_mk1>);
recipes.remove(<projecte:collector_mk2>);
recipes.remove(<projecte:collector_mk3>);
recipes.remove(<projecte:relay_mk1>);
recipes.remove(<projecte:relay_mk2>);
recipes.remove(<projecte:relay_mk3>);
recipes.remove(<projecte:item.pe_gem_density>);
recipes.remove(<projecte:item.pe_harvest_god>);
recipes.remove(<projecte:item.pe_time_watch>);
recipes.remove(<projecte:item.pe_gem_armor_0>);
recipes.remove(<projecte:item.pe_gem_armor_1>);
recipes.remove(<projecte:item.pe_gem_armor_2>);
recipes.remove(<projecte:item.pe_gem_armor_3>);
recipes.remove(<magneticraft:crafting:6>);
recipes.remove(<actuallyadditions:item_boots_emerald>);
recipes.remove(<actuallyadditions:item_pants_emerald>);
recipes.remove(<actuallyadditions:item_chest_emerald>);
recipes.remove(<actuallyadditions:item_helm_emerald>);
recipes.remove(<actuallyadditions:item_boots_obsidian>);
recipes.remove(<actuallyadditions:item_pants_obsidian>);
recipes.remove(<actuallyadditions:item_chest_obsidian>);
recipes.remove(<actuallyadditions:item_helm_obsidian>);
recipes.remove(<nuclearcraft:manufactory_idle>);
recipes.remove(<abyssalcraft:necronomicon>);
recipes.remove(<tcomplement:manyullyn_helmet>);
recipes.remove(<tcomplement:manyullyn_chestplate>);
recipes.remove(<tcomplement:manyullyn_leggings>);
recipes.remove(<tcomplement:manyullyn_boots>);
recipes.remove(<avaritia:extreme_crafting_table>);
recipes.remove(<quark:reed_block>);
recipes.remove(<mekanismtools:steelboots>);
recipes.remove(<mekanismtools:steelleggings>);
recipes.remove(<mekanismtools:steelchestplate>);
recipes.remove(<mekanismtools:steelhelmet>);
recipes.remove(<mekanismtools:steelsword>);
recipes.remove(<mekanismtools:steelhoe>);
recipes.remove(<mekanismtools:steelshovel>);
recipes.remove(<mekanismtools:steelaxe>);
recipes.remove(<mekanismtools:steelpickaxe>);
recipes.remove(<mekanismtools:steelpaxel>);
recipes.remove(<mekanismtools:bronzesword>);
recipes.remove(<mekanismtools:bronzehoe>);
recipes.remove(<mekanismtools:bronzeshovel>);
recipes.remove(<mekanismtools:bronzeaxe>);
recipes.remove(<mekanismtools:bronzepickaxe>);
recipes.remove(<mekanismtools:bronzepaxel>);
recipes.remove(<mekanismtools:bronzeboots>);
recipes.remove(<mekanismtools:bronzeleggings>);
recipes.remove(<mekanismtools:bronzechestplate>);
recipes.remove(<mekanismtools:bronzehelmet>);
recipes.remove(<projecte:dm_pedestal>);
recipes.remove(<botania:altar>);
recipes.remove(<xreliquary:mob_charm>.withTag({type: 8 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 9 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 10 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 11 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 12 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 13 as byte}));
recipes.remove(<xreliquary:mob_charm_belt>);
recipes.remove(<xreliquary:mob_charm>.withTag({type: 7 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 6 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 5 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 4 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 3 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 2 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 1 as byte}));
recipes.remove(<xreliquary:mob_charm>.withTag({type: 0 as byte}));
recipes.remove(<xreliquary:void_tear>);
recipes.remove(<immersiveengineering:metal:38>);
recipes.remove(<immersiveengineering:metal:39>);
recipes.remove(<immersiveengineering:metal:40>);
recipes.remove(<immersiveengineering:metal:37>);
recipes.remove(<immersiveengineering:metal:36>);
recipes.remove(<immersiveengineering:metal:35>);
recipes.remove(<immersiveengineering:metal:34>);
recipes.remove(<immersiveengineering:metal:33>);
recipes.remove(<immersiveengineering:metal:32>);
recipes.remove(<immersiveengineering:metal:31>);
recipes.remove(<immersiveengineering:metal:30>);
recipes.remove(<embers:hoe_tin>);
recipes.remove(<embers:sword_tin>);
recipes.remove(<embers:shovel_tin>);
recipes.remove(<embers:axe_tin>);
recipes.remove(<embers:pickaxe_tin>);
recipes.remove(<embers:hoe_nickel>);
recipes.remove(<embers:sword_nickel>);
recipes.remove(<embers:shovel_nickel>);
recipes.remove(<embers:axe_nickel>);
recipes.remove(<embers:pickaxe_nickel>);
recipes.remove(<embers:axe_silver>);
recipes.remove(<embers:pickaxe_silver>);
recipes.remove(<embers:sword_copper>);
recipes.remove(<embers:hoe_copper>);
recipes.remove(<embers:shovel_copper>);
recipes.remove(<embers:axe_copper>);
recipes.remove(<embers:pickaxe_copper>);
recipes.remove(<embers:hoe_electrum>);
recipes.remove(<embers:sword_electrum>);
recipes.remove(<embers:shovel_electrum>);
recipes.remove(<embers:axe_electrum>);
recipes.remove(<embers:pickaxe_electrum>);
recipes.remove(<embers:hoe_bronze>);
recipes.remove(<embers:sword_bronze>);
recipes.remove(<embers:shovel_bronze>);
recipes.remove(<embers:axe_bronze>);
recipes.remove(<embers:pickaxe_bronze>);
recipes.remove(<embers:hoe_aluminum>);
recipes.remove(<embers:sword_aluminum>);
recipes.remove(<embers:shovel_aluminum>);
recipes.remove(<embers:axe_aluminum>);
recipes.remove(<embers:pickaxe_aluminum>);
recipes.remove(<embers:sword_lead>);
recipes.remove(<embers:hoe_lead>);
recipes.remove(<embers:shovel_lead>);
recipes.remove(<embers:axe_lead>);
recipes.remove(<embers:axe_lead>);
recipes.remove(<embers:pickaxe_lead>);
recipes.remove(<embers:sword_silver>);
recipes.remove(<embers:hoe_silver>);
recipes.remove(<embers:shovel_silver>);
recipes.remove(<embers:plate_bronze>);
recipes.remove(<embers:plate_nickel>);
recipes.remove(<embers:plate_electrum>);
recipes.remove(<embers:plate_tin>);
recipes.remove(<embers:plate_aluminum>);
recipes.remove(<embers:plate_dawnstone>);
recipes.remove(<embers:plate_silver>);
recipes.remove(<embers:plate_lead>);
recipes.remove(<embers:plate_gold>);
recipes.remove(<embers:plate_iron>);
recipes.remove(<embers:plate_copper>);
recipes.remove(<embers:plate_dawnstone>);
recipes.remove(<minecraft:flint_and_steel>);
recipes.remove(<tcomplement:materials:1>);
recipes.remove(<tcomplement:materials:0>);
recipes.remove(<tcomplement:materials:10>);
recipes.remove(<tcomplement:materials:20>);
recipes.remove(<minecraft:bucket>);
recipes.remove(<solarflux:mirror>);
recipes.remove(<extendedcrafting:crafting_table>);
recipes.remove(<overloaded:nether_star_block>);
recipes.remove(<extendedcrafting:handheld_table>);
recipes.remove(<aroma1997sdimension:dimensionchanger>);
recipes.remove(<aroma1997sdimension:miningmultitool>);
recipes.remove(<tp:wooden_shears>);
recipes.remove(<chiselsandbits:wrench_wood>);
recipes.remove(<mob_grinding_utils:saw_upgrade:5>);
recipes.remove(<abyssalcraft:ironp> * 2);
recipes.remove(<quantumflux:magnet>);
recipes.remove(<mekanism:basicblock:8>);
recipes.remove(<quantumstorage:trashcanfluid>);
recipes.remove(<quantumstorage:trashcan>);
recipes.remove(<randomthings:timeinabottle>);
recipes.remove(<xreliquary:alkahestry_tome:1>);
recipes.remove(<tp:iron_spear>);
recipes.remove(<quark:soul_sandstone>);
recipes.remove(<tconstruct:rack>);
recipes.removeShapeless(<galacticraftplanets:carbon_fragments> * 4, [ <minecraft:coal:1>]);
recipes.removeShapeless(<mysticalagriculture:crafting:7>, [<minecraft:dye>, <minecraft:dye:14>, <minecraft:dye:6>, <minecraft:dye:13>]);
recipes.removeShapeless(<bigreactors:blockgraphite>, [<bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>]);
recipes.removeShapeless(<simplyjetpacks:itemjetpack>, [<simplyjetpacks:itemjetpack:*>, <nuclearcraft:rad_shielding:2>]);
recipes.removeShapeless(<simplyjetpacks:itemjetpack>, [<simplyjetpacks:itemjetpack:*>, <nuclearcraft:rad_shielding:1>]);
recipes.removeShapeless(<simplyjetpacks:itemjetpack>, [<simplyjetpacks:itemjetpack:*>, <nuclearcraft:rad_shielding>]);
recipes.removeShaped(<minecraft:diamond>, [[<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>],[<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>], [<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>]]);
recipes.removeShapeless(<minecraft:diamond>, [<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>]);
recipes.removeShapeless(<extraplanets:cloth> * 8, [<ore:blockWool>, <ore:blockWool>, <ore:blockWool>, <ore:blockWool>]);
recipes.removeShapeless(<guideapi:bloodmagic-guide>, [<minecraft:book>, <ore:blockGlass>, <ore:feather>]);
recipes.removeShapeless(<patchouli:guide_book>, [<pneumaticcraft:ingot_iron_compressed>, <minecraft:book>]);
recipes.removeShaped(<extraplanets:advanced_launch_pad:3> * 5, [[null, null, null],[<extraplanets:tier11_items:6>, <extraplanets:tier11_items:6>, <extraplanets:tier11_items:6>], [<thermalfoundation:material:134>, <thermalfoundation:material:134>, <thermalfoundation:material:134>]]);
recipes.removeShaped(<extraplanets:advanced_launch_pad> * 5, [[null, null, null],[<galacticraftplanets:item_basic_asteroids:6>, <galacticraftplanets:item_basic_asteroids:6>, <galacticraftplanets:item_basic_asteroids:6>], [<galacticraftplanets:item_basic_asteroids>, <galacticraftplanets:item_basic_asteroids>, <galacticraftplanets:item_basic_asteroids>]]);
//Don't touch me!
//#Add
recipes.addShapeless(<mekanism:machineblock2:11>.withTag({tier: 4}), [<mekanism:machineblock2:11>.withTag({tier: 4})]);
recipes.addShapeless(<contenttweaker:neutral_steel_6>, [<contenttweaker:neutral_steel_5>,<contenttweaker:neutral_steel_5>,<contenttweaker:neutral_steel_5>]);
recipes.addShaped(<extraplanets:ultimate_battery:100>, [[<ore:oreWhiteGem>, <ore:oreRedGem>, <ore:oreBlueGem>],[<ore:blockCarbon>, <ore:blockPalladium>, <ore:blockMagnesium>], [<ore:ingotTungsten>, <extraplanets:advanced_battery:*>, <ore:ingotZinc>]]);
recipes.addShapeless(<minecraft:coal:1>, [<abyssalcraft:charcoal>]);
recipes.addShaped(<abyssalcraft:psdl>, [[<ore:gemInfusedLavaCrystal>, <embers:ember_cluster>, <ore:gemInfusedLavaCrystal>],[<abyssalcraft:luminousthistle>, <ore:oreCoraliumStone>, <abyssalcraft:luminousthistle>], [<ore:ballRedstoneAlloy>, <abyssalcraft:abybrick>, <ore:ballRedstoneAlloy>]]);
recipes.addShaped(<industrialforegoing:laser_base>, [[<ore:plasticLightGray>, <ore:ingotFerroboron>, <ore:plasticLightGray>],[<ore:ingotFerroboron>, <thermalfoundation:material:295>, <ore:ingotFerroboron>], [<ore:ingotRefinedGlowstone>, <nuclearcraft:part:12>, <ore:ingotRefinedGlowstone>]]);
recipes.addShaped(<industrialforegoing:laser_drill>, [[<ore:plasticLightGray>, <ore:ingotFerroboron>, <ore:plasticLightGray>],[<ore:ingotRefinedObsidian>, <industrialforegoing:laser_lens>, <ore:ingotRefinedObsidian>], [<ore:ingotFerroboron>, <nuclearcraft:part:12>, <ore:ingotFerroboron>]]);
recipes.addShaped(<industrialforegoing:tree_fluid_extractor>, [[<ore:ingotInvar>, <ore:ingotRedAlloy>, <ore:ingotInvar>],[<ore:ingotInvar>, <thermalexpansion:frame>, <ore:ingotInvar>], [<ore:ingotInvar>, <ore:blockElectrotine>, <ore:ingotInvar>]]);
recipes.addShaped(<industrialforegoing:mob_relocator>, [[<ore:itemRubber>, <extrautils2:spike_iron>, <ore:itemRubber>],[<ore:ingotElectrotineAlloy>, <thermalexpansion:frame>, <ore:ingotElectrotineAlloy>], [<ore:ingotRedstoneAlloy>, <ore:gearSignalum>, <ore:ingotRedstoneAlloy>]]);
recipes.addShaped(<industrialforegoing:crop_recolector>, [[<ore:itemRubber>, <mekanismtools:ironpaxel>, <ore:itemRubber>],[<ore:heavyPlateTungsten>, <thermalexpansion:frame>, <ore:heavyPlateTungsten>], [<ore:gearPlatinum>, <ore:scaffoldingSteel>, <ore:gearPlatinum>]]);
recipes.addShaped(<industrialforegoing:animal_resource_harvester>, [[<ore:itemRubber>, <ore:itemRubber>, <ore:itemRubber>],[<ore:toolShears>, <thermalexpansion:frame>, <ore:toolShears>], [<ore:gearNickel>, <ore:PorcelainTank>, <ore:gearNickel>]]);
recipes.addShaped(<industrialforegoing:latex_processing_unit>, [[<ore:ingotTitanium>, <ore:ingotRedstoneAlloy>, <ore:ingotTitanium>],[<ore:scaffoldingSteel>, <thermalexpansion:frame>, <ore:scaffoldingSteel>], [<ore:gearConstantan>, <furnaceoverhaul:iron_furnace>, <ore:gearConstantan>]]);
recipes.addShaped(<industrialforegoing:mob_slaughter_factory>, [[<ore:itemRubber>, <ore:gearPlatinum>, <ore:itemRubber>],[<ore:ballCrystallineAlloy>, <thermalexpansion:frame>, <ore:ballCrystallineAlloy>], [<ore:skullZombieElectrode>, <ore:ingotRedstoneAlloy>, <ore:skullZombieElectrode>]]);
recipes.addShaped(<extrautils2:machine>.withTag({Type: "extrautils2:generator_slime"}), [[<ore:slimeball>, <ore:slimeball>, <ore:slimeball>],[<ore:slimeball>, <ore:blockSlime>, <ore:slimeball>], [<ore:dustRedstone>, <extrautils2:machine>.withTag({Type: "extrautils2:generator"}), <ore:dustRedstone>]]);
recipes.addShaped(<exnihilocreatio:crook_diorite>, [[<ore:stoneDiorite>, <ore:stoneDiorite>, null],[null, <ore:stoneDiorite>, null], [null, <ore:stoneDiorite>, null]]);
recipes.addShaped(<exnihilocreatio:crook_andesite>, [[<ore:stoneAndesite>, <ore:stoneAndesite>, null],[null, <ore:stoneAndesite>, null], [null, <ore:stoneAndesite>, null]]);
recipes.addShaped(<exnihilocreatio:crook_stone>, [[<ore:cobblestone>, <ore:cobblestone>, null],[null, <ore:cobblestone>, null], [null, <ore:cobblestone>, null]]);
recipes.addShaped(<exnihilocreatio:crook_granite>, [[<ore:stoneGranite>, <ore:stoneGranite>, null],[null, <ore:stoneGranite>, null], [null, <ore:stoneGranite>, null]]);
recipes.addShaped(<extraplanets:advanced_launch_pad> * 5, [[null, null, null],[<galacticraftplanets:item_basic_asteroids:6>, <galacticraftplanets:item_basic_asteroids:6>, <galacticraftplanets:item_basic_asteroids:6>], [<ore:ingotTitanium>, <ore:ingotTitanium>, <ore:ingotTitanium>]]);
recipes.addShaped(<extraplanets:advanced_launch_pad:3> * 5, [[null, null, null],[<extraplanets:tier11_items:6>, <extraplanets:tier11_items:6>, <extraplanets:tier11_items:6>], [<ore:ingotPlatinum>, <ore:ingotPlatinum>, <ore:ingotPlatinum>]]);
recipes.addShaped(<chancecubes:silk_touch_pendant>, [[<mysticalagriculture:crafting:23>, <ore:blockLapis>, <mysticalagriculture:crafting:23>],[<mysticalagriculture:crafting:23>, <apotheosis:hellshelf>, <mysticalagriculture:crafting:23>], [<mysticalagriculture:crafting:23>, <ore:blockLapis>, <mysticalagriculture:crafting:23>]]);
recipes.addShaped(<magneticraft:heat_pipe> * 4, [[<ceramics:porcelain:15>, <ore:ingotAluminum>, <ceramics:porcelain:15>],[<ore:ingotAluminum>, <ore:ingotCopper>, <ore:ingotAluminum>], [<ceramics:porcelain:15>, <ore:ingotAluminum>, <ceramics:porcelain:15>]]);
recipes.addShapeless(<magneticraft:steam_engine>, [<ore:paper>,<magneticraft:small_tank>]);
recipes.addShapeless(<magneticraft:steam_turbine>, [<ore:paper>,<magneticraft:steam_boiler>]);
recipes.addShapeless(<magneticraft:solar_mirror>, [<ore:paper>,<magneticraft:crafting:3>]);
recipes.addShapeless(<magneticraft:solar_tower>, [<ore:paper>,<magneticraft:connector>]);
recipes.addShaped(<tconstruct:rack>.withTag({textureBlock: {id: "minecraft:wooden_slab", Count: 1 as byte, Damage: 0 as short}}), [[<minecraft:wooden_slab>, <minecraft:wooden_slab>, <minecraft:wooden_slab>],[null, <minecraft:wooden_slab>, null], [null, null, null]]);
recipes.addShapeless(<randomthings:ingredient:0>, [<minecraft:brown_mushroom>,<exnihilocreatio:item_material:3>]);
recipes.addShaped(<blockcraftery:editable_block> * 2, [[<ore:stickWood>, null, <ore:stickWood>],[null, <extraplanets:cloth>, null], [<ore:stickWood>, null, <ore:stickWood>]]);
recipes.addShaped(<extraplanets:cloth> * 8, [[<ore:blockWool>, <ore:blockWool>, null],[<ore:blockWool>, <ore:blockWool>, null], [null, null, null]]);
recipes.addShapeless(<projecte:item.pe_klein_star:5>, [<contenttweaker:klein_star_6_inert>]);
recipes.addShapeless(<contenttweaker:klein_star_6_inert>, [<projecte:item.pe_klein_star:5>]);
recipes.addShaped(<quark:soul_sandstone> * 2, [[<ore:soulSand>, <ore:soulSand>, <ore:soulSand>],[<ore:soulSand>, null, <ore:soulSand>], [<ore:soulSand>, <ore:soulSand>, <ore:soulSand>]]);
recipes.addShapeless(<magneticraft:oil_heater>, [<actuallyadditions:item_misc:7>,<ore:paper>]);
recipes.addShapeless(<minecraft:string> * 8, [<erebus:silk>]);
recipes.addShapeless(<bigreactors:blockgraphite>, [<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>,<ore:ingotGraphite>]);
recipes.addShapeless(<thermalsolars:itemtitaniumingot>, [<galacticraftplanets:item_basic_asteroids>]);
recipes.addShapeless(<galacticraftplanets:item_basic_asteroids>, [<ore:ingotTitanium>]);
recipes.addShaped(<actuallyadditions:block_fluid_placer>, [[null, <actuallyadditions:item_crystal:5>, null],[<extracells:certustank>, <actuallyadditions:block_misc:7>, <extracells:certustank>], [null, <actuallyadditions:item_crystal:5>, null]]);
recipes.addShaped(<minecraft:apple>, [[<ore:foodCongealedmagmacream>, <ore:foodCongealedmagmacream>, <ore:foodCongealedmagmacream>],[<ore:foodCongealedmagmacream>, <natura:edibles:10>, <ore:foodCongealedmagmacream>], [<ore:foodCongealedmagmacream>, <ore:foodCongealedmagmacream>, <ore:foodCongealedmagmacream>]]);
recipes.addShaped(<simplyjetpacks:itemfluxpack:8>, [[null, <thermalexpansion:cell>, null],[<ore:ingotEnderium>, <simplyjetpacks:itemfluxpack:7>, <ore:ingotEnderium>], [<ore:ingotLead>, <thermalfoundation:material:515>, <ore:ingotLead>]]);
recipes.addShaped(<simplyjetpacks:itemfluxpack:7>, [[null, <thermalexpansion:cell>, null],[<ore:ingotElectrum>, <simplyjetpacks:itemfluxpack:6>, <ore:ingotElectrum>], [<ore:ingotLead>, <thermalfoundation:material:515>, <ore:ingotLead>]]);
recipes.addShaped(<simplyjetpacks:itemfluxpack:6>, [[<ore:ingotLead>, <thermalexpansion:cell>, <ore:ingotLead>],[<ore:ingotLead>, <simplyjetpacks:metaitem:4>, <ore:ingotLead>], [null, null, null]]);
recipes.addShaped(<tp:iron_spear>, [[null, null, <ore:ingotIron>],[null, <ore:stickTreatedWood>, null], [<ore:stickTreatedWood>, null, null]]);
recipes.addShaped(<minecraft:fire_charge> * 3, [[<ore:gunpowder>, <ore:itemBlazePowder>, <ore:itemFlint>],[<minecraft:coal:*>, <ore:dustSulfur>, <ore:ingotSteel>], [null, null, null]]);
recipes.addShapeless(<mysticalagriculture:crafting:7>, [<ore:dye>,<ore:dye>,<ore:dye>,<ore:dye>]);
recipes.addShapedMirrored(<abyssalcraft:ironp> * 2, [[null, <ore:ingotIron>, null],[null, <ore:plateIron>, null], [null, null, null]]);
recipes.addShapedMirrored(<chiselsandbits:wrench_wood>, [[null, null, null],[null, null, <ore:plankWood>], [null, <ore:plankWood>, <ore:stickWood>]]);
recipes.addShapedMirrored(<tp:wooden_shears>, [[<ore:stickWood>, null, null],[<ore:plankWood>, <ore:stickWood>, null], [null, null, null]]);
recipes.addShapeless(<galacticraftplanets:carbon_fragments> * 4, [<minecraft:coal:1>,<minecraft:coal:1>]);
recipes.addShaped(<enderio:item_basic_capacitor>, [[null, <ore:nuggetGold>, <enderio:item_capacitor_grainy>],[<ore:nuggetGold>, <ore:ingotCopper>, <ore:nuggetGold>], [<enderio:item_capacitor_grainy>, <ore:nuggetGold>, null]]);
recipes.addShaped(<enderio:item_capacitor_silver>, [[null, <ore:nuggetSilver>, <enderio:item_capacitor_grainy>],[<ore:nuggetSilver>, <ore:ingotLead>, <ore:nuggetSilver>], [<enderio:item_capacitor_grainy>, <ore:nuggetSilver>, null]]);
recipes.addShapedMirrored(<magneticraft:ingots:14>, [[<extraplanets:tier8_items:5>, null, null],[null, null, null], [null, null, null]]);
recipes.addShapedMirrored(<extraplanets:tier8_items:5>, [[<magneticraft:ingots:14>, null, null],[null, null, null], [null, null, null]]);
recipes.addShapeless(<extraplanets:pluto:7>, [<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>,<ore:ingotTungsten>]);
recipes.addShaped(<extrautils2:opinium>, [[null, <ore:blockCoal>, null],[<ore:blockCoal>, <ore:blockIron>, <ore:blockCoal>], [null, <ore:blockCoal>, null]]);
recipes.addShapedMirrored(<magneticraft:crafting:3> * 2, [[null, null, null],[<ore:wireCopper>, <ore:ingotTungsten>, <ore:wireCopper>], [null, null, null]]);
recipes.addShaped(<tp:watering_can_upgrade>, [[<ore:ingotLead>, <industrialforegoing:fertilizer>, null],[<ore:ingotLead>, <tp:watering_can>, <ore:ingotLead>], [null, <ore:ingotLead>, null]]);
recipes.addShaped(<equivalentintegrations:soulbound_talisman>, [[null, <projecte:item.pe_soul_stone>, null],[<projecte:item.pe_soul_stone>, <projecte:transmutation_table>, <projecte:item.pe_soul_stone>], [null, <projecte:item.pe_soul_stone>, null]]);
recipes.addShaped(<extraplanets:tier8_items:1>, [[<extraplanets:tier8_items:4>, <minecraft:wool:14>, <extraplanets:tier8_items:4>],[<extraplanets:tier8_items:4>, <galacticraftcore:fuel_canister_partial:1>, <extraplanets:tier8_items:4>], [<extraplanets:tier8_items:3>, <galacticraftcore:air_vent>, <extraplanets:tier8_items:3>]]);
recipes.addShaped(<quark:reed_block>, [[<minecraft:reeds>, <minecraft:reeds>, <minecraft:reeds>],[<minecraft:reeds>, null, <minecraft:reeds>], [<minecraft:reeds>, <minecraft:reeds>, <minecraft:reeds>]]);
recipes.addShaped(<mekanism:basicblock2:7> * 4, [[null, <ore:ingotSteel>, null],[<ore:ingotSteel>, <ore:blockSheetmetalIron>, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
recipes.addShaped(<astralsorcery:itemwand>, [[null, <ore:gemAquamarine>, <ore:enderpearl>],[null, <ore:stoneMarble>, <ore:gemAquamarine>], [<ore:stoneMarble>, null, null]]);
recipes.addShaped(<astralsorcery:blockaltar>, [[<ore:gemAquamarine>, <astralsorcery:blockblackmarble>, <ore:gemAquamarine>],[<ore:stoneMarble>, <ore:workbench>, <ore:stoneMarble>], [<ore:stoneMarble>, null, <ore:stoneMarble>]]);
recipes.addShapeless(<botania:fertilizer> * 3, [<lordcraft:crystal_basic_light>,<ore:dye>,<ore:dye>,<ore:dye>,<ore:dye>]);
recipes.addShaped(<embers:stone_edge>, [[null, null, null],[<embers:stairs_caminite_brick>, null, <embers:stairs_caminite_brick>], [<embers:block_caminite_brick>, <embers:block_caminite_brick>, <embers:block_caminite_brick>]]);
recipes.addShaped(<extraplanets:tools:2>, [[<minecraft:string>, <minecraft:string>, <minecraft:string>],[<minecraft:string>, <minecraft:string>, <minecraft:string>], [null, null, null]]);
recipes.addShaped(<magneticraft:copper_coil> * 16, [[<ore:wireCopper>, <ore:wireCopper>, <ore:wireCopper>],[<ore:wireCopper>, <ore:ingotTitanium>, <ore:wireCopper>], [<ore:wireCopper>, <ore:wireCopper>, <ore:wireCopper>]]);
recipes.addShaped(<lootbags:loot_opener>, [[<minecraft:dye:4>, <minecraft:dye:4>, <minecraft:dye:4>],[<ore:ingotSilver>, <ore:chest>, <ore:ingotSilver>], [<minecraft:dye:4>, <minecraft:dye:4>, <minecraft:dye:4>]]);
recipes.addShaped(<magneticraft:pumpjack_drill>, [[<ore:ingotZinc>, null, <ore:ingotZinc>],[<ore:ingotZinc>, <magneticraft:small_tank>, <ore:ingotZinc>], [<ore:ingotZinc>, null, <ore:ingotZinc>]]);
recipes.addShaped(<magneticraft:wind_turbine>, [[<magneticraft:multiblock_column>, <magneticraft:crafting:3>, <ore:fabricHemp>],[<magneticraft:crafting:3>, <magneticraft:battery_item_low>, <ore:fabricHemp>], [<magneticraft:multiblock_column>, <magneticraft:crafting:3>, <ore:fabricHemp>]]);
recipes.addShaped(<magneticraft:thermopile>, [[<ore:plateTungsten>, <magneticraft:crafting:3>, <ore:plateTungsten>],[<ore:plateTungsten>, <magneticraft:battery_item_low>, <ore:plateTungsten>], [<ore:plateTungsten>, <magneticraft:crafting:3>, <ore:plateTungsten>]]);
recipes.addShaped(<magneticraft:multiblock_parts:3> * 4, [[<ore:ingotTungsten>, <ore:ingotTungsten>, <ore:ingotTungsten>],[<ore:ingotTungsten>, <ore:blockIron>, <ore:ingotTungsten>], [<ore:ingotTungsten>, <ore:ingotTungsten>, <ore:ingotTungsten>]]);
recipes.addShaped(<magneticraft:multiblock_column> * 4, [[null, <ore:plateTungsten>, null],[<ore:plateTungsten>, <ore:stone>, <ore:plateTungsten>], [null, <ore:plateTungsten>, null]]);
recipes.addShaped(<magneticraft:multiblock_parts:4> * 4, [[<ore:ingotTungsten>, <ore:plateCopper>, <ore:ingotTungsten>],[<ore:plateCopper>, <ore:stone>, <ore:plateCopper>], [<ore:ingotTungsten>, <ore:plateCopper>, <ore:ingotTungsten>]]);
recipes.addShaped(<magneticraft:multiblock_parts> * 4, [[<ore:stone>, <ore:stone>, <ore:stone>],[<ore:ingotZinc>, <ore:blockIron>, <ore:ingotZinc>], [<ore:plateTungsten>, <ore:plateTungsten>, <ore:plateTungsten>]]);
recipes.addShaped(<magneticraft:battery>, [[<magneticraft:multiblock_parts:1>, <magneticraft:multiblock_parts:1>, <magneticraft:multiblock_parts:1>],[<magneticraft:battery_item_medium>, <magneticraft:battery_item_medium>, <magneticraft:battery_item_medium>], [<magneticraft:multiblock_parts:1>, <magneticraft:multiblock_parts:1>, <magneticraft:multiblock_parts:1>]]);
recipes.addShaped(<openblocks:scaffolding> * 8, [[<ore:slabWood>, <ore:slabWood>, <ore:slabWood>],[null, <ore:stickWood>, null], [<ore:stickWood>, null, <ore:stickWood>]]);
recipes.addShaped(<magneticraft:multiblock_parts:1> * 4, [[<ore:ingotZinc>, <magneticraft:crafting:3>, <ore:ingotZinc>],[<magneticraft:crafting:3>, <ore:stone>, <magneticraft:crafting:3>], [<ore:ingotZinc>, <magneticraft:crafting:3>, <ore:ingotZinc>]]);
recipes.addShaped(<magneticraft:steam_boiler>, [[null, <magneticraft:multiblock_parts:5>, null],[<magneticraft:multiblock_parts:5>, <magneticraft:small_tank>, <magneticraft:multiblock_parts:5>], [null, <magneticraft:multiblock_parts:5>, null]]);
recipes.addShaped(<magneticraft:multiblock_parts:5> * 4, [[<ore:ingotIron>, <ore:ingotZinc>, <ore:ingotIron>],[<ore:plateTungsten>, <ore:stone>, <ore:plateTungsten>], [<ore:ingotIron>, <ore:ingotZinc>, <ore:ingotIron>]]);
recipes.addShaped(<magneticraft:inserter>, [[null, <ore:ingotTungsten>, null],[<ore:ingotIron>, null, <ore:ingotTungsten>], [<ore:plateTungsten>, <ore:plateTungsten>, <ore:plateTungsten>]]);
recipes.addShaped(<magneticraft:conveyor_belt>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>],[<ore:ingotTungsten>, <ore:ingotTungsten>, <ore:ingotTungsten>], [<ore:ingotTungsten>, null, <ore:ingotTungsten>]]);
recipes.addShaped(<magneticraft:battery_item_medium>.withTag({}), [[<ore:ingotZinc>, <ore:dustSulfur>, <ore:ingotZinc>],[<ore:ingotZinc>, <magneticraft:battery_item_low>, <ore:ingotZinc>], [<ore:ingotZinc>, <ore:dustSulfur>, <ore:ingotZinc>]]);
recipes.addShaped(<magneticraft:battery_item_low>.withTag({}), [[<ore:ingotZinc>, <ore:dustSulfur>, <ore:ingotZinc>],[<ore:ingotZinc>, <ore:dustSulfur>, <ore:ingotZinc>], [<ore:ingotZinc>, <ore:dustSulfur>, <ore:ingotZinc>]]);
recipes.addShaped(<magneticraft:electric_furnace>, [[<ore:ingotBrick>, <ore:ingotBrick>, <ore:ingotBrick>],[<ore:ingotBrick>, <furnaceoverhaul:iron_furnace>, <ore:ingotBrick>], [<magneticraft:battery_item_medium>, <magneticraft:brick_furnace>, <magneticraft:battery_item_medium>]]);
recipes.addShaped(<immersiveengineering:tool>, [[null, <ore:ingotIron>, <ore:fiberHemp>],[null, <ore:stickWood>, <ore:ingotIron>], [<ore:stickWood>, null, null]]);
recipes.addShaped(<minecraft:leather> * 3, [[<ore:materialCloth>, <ore:materialCloth>, <ore:materialCloth>],[null, <ore:materialCloth>, null], [<ore:materialCloth>, <ore:materialCloth>, <ore:materialCloth>]]);
recipes.addShaped(<enderio:item_material:9>, [[null, <ore:stickWood>, null],[<ore:stickWood>, <ore:plankWood>, <ore:stickWood>], [null, <ore:stickWood>, null]]);
recipes.addShaped(<mysticalagriculture:crafting:50>, [[<ore:essenceInferium>, <ore:ingotGold>, <ore:essenceInferium>],[<minecraft:dye:15>, <ore:ingotBaseEssence>, <minecraft:dye:15>], [<ore:essenceInferium>, <minecraft:dye:15>, <ore:essenceInferium>]]);
recipes.addShaped(<portality:frame> * 8, [[<projectred-core:resource_item:104>, <ore:gemQuartzBlack>, <projectred-core:resource_item:104>],[<ore:gemQuartzBlack>, null, <ore:gemQuartzBlack>], [<projectred-core:resource_item:104>, <ore:gemQuartzBlack>, <projectred-core:resource_item:104>]]);
recipes.addShaped(<portality:controller>, [[<portality:frame>, <ore:ingotElectrotineAlloy>, <portality:frame>],[<ore:ingotElectrotineAlloy>, <actuallyadditions:block_misc:2>, <ore:ingotElectrotineAlloy>], [<portality:frame>, <ore:ingotElectrotineAlloy>, <portality:frame>]]);
recipes.addShaped(<tp:cobblegen_block>, [[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>],[<ceramics:clay_bucket>.withTag({fluids: {FluidName: "water", Amount: 1000}}), <ore:blockGlassColorless>, <ceramics:clay_bucket>.withTag({fluids: {FluidName: "lava", Amount: 1000}})], [<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>]]);
recipes.addShaped(<minecraft:arrow> * 4, [[null,<minecraft:flint>,null], [<tconstruct:fletching>.withTag({Material: "leaf"}),<ore:stickWood>,<tconstruct:fletching>.withTag({Material: "leaf"})], [null,<tconstruct:fletching>.withTag({Material: "leaf"}),null]]);
recipes.addShapeless(<minecraft:string> * 3, [<exnihilocreatio:item_mesh:1>]);
recipes.addShaped(<erebus:silk>, [[<harvestcraft:wovencottonitem>, <harvestcraft:wovencottonitem>, null],[<harvestcraft:wovencottonitem>, <harvestcraft:wovencottonitem>, null], [null, null, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:7>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch:6>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:6>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch:5>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:5>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch:4>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:4>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch:3>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:3>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch:2>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:2>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch:1>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch:1>, [[<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberoutputhatch>, <modularmachinery:itemmodularium>], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:7>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch:6>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:6>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch:5>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:5>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch:4>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:4>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch:3>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:3>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch:2>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:2>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch:1>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch:1>, [[null, <embers:ember_emitter>, null],[<modularmachinery:itemmodularium>, <modulardiversity:blockemberinputhatch>, <modularmachinery:itemmodularium>], [<embers:plate_dawnstone>, <modularmachinery:itemmodularium>, <embers:plate_dawnstone>]]);
recipes.addShaped(<modulardiversity:blockemberoutputhatch>, [[null, <embers:plate_dawnstone>, null],[null, <modularmachinery:blockcasing>, null], [null, <embers:ember_receiver>, null]]);
recipes.addShaped(<modulardiversity:blockemberinputhatch>, [[null, <embers:ember_emitter>, null],[null, <modularmachinery:blockcasing>, null], [null, <embers:plate_dawnstone>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:7>, [[<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyoutputhatch:6>, <modularmachinery:itemmodularium>], [null, <thermaldynamics:duct_0>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:6>, [[<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyoutputhatch:5>, <modularmachinery:itemmodularium>], [null, <thermaldynamics:duct_0>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:5>, [[<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyoutputhatch:4>, <modularmachinery:itemmodularium>], [null, <thermaldynamics:duct_0>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:4>, [[<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyoutputhatch:3>, <modularmachinery:itemmodularium>], [null, <thermaldynamics:duct_0>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:3>, [[<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyoutputhatch:2>, <modularmachinery:itemmodularium>], [null, <thermaldynamics:duct_0>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:2>, [[<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyoutputhatch:1>, <modularmachinery:itemmodularium>], [null, <thermaldynamics:duct_0>, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:7>, [[null, <thermaldynamics:duct_0>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyinputhatch:6>, <modularmachinery:itemmodularium>], [<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:6>, [[null, <thermaldynamics:duct_0>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyinputhatch:5>, <modularmachinery:itemmodularium>], [<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:5>, [[null, <thermaldynamics:duct_0>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyinputhatch:4>, <modularmachinery:itemmodularium>], [<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:4>, [[null, <thermaldynamics:duct_0>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyinputhatch:3>, <modularmachinery:itemmodularium>], [<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:3>, [[null, <thermaldynamics:duct_0>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyinputhatch:2>, <modularmachinery:itemmodularium>], [<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:2>, [[null, <thermaldynamics:duct_0>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockenergyinputhatch:1>, <modularmachinery:itemmodularium>], [<minecraft:redstone>, <modularmachinery:itemmodularium>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:7>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:6>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:6>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:5>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:5>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:4>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:4>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:3>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:3>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:2>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:2>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:1>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:7>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:6>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:6>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:5>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:5>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:4>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:4>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:3>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:3>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:2>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:2>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:1>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockoutputbus:6>, [[<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:5>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:5>, [[<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:4>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:4>, [[<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:3>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:3>, [[<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:2>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:2>, [[<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:1>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:6>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:5>, <modularmachinery:itemmodularium>], [<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:5>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:4>, <modularmachinery:itemmodularium>], [<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:4>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:3>, <modularmachinery:itemmodularium>], [<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:3>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:2>, <modularmachinery:itemmodularium>], [<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:2>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:1>, <modularmachinery:itemmodularium>], [<ore:chest>, <modularmachinery:itemmodularium>, <ore:chest>]]);
recipes.addShaped(<modulardiversity:blockmanaoutputhatch>, [[<modularmachinery:blockcasing:4>, <botania:quartztypeelf>, <modularmachinery:blockcasing:4>],[<botania:quartztypeelf>, <botania:spreader>, <botania:quartztypeelf>], [<modularmachinery:blockcasing:4>, <botania:quartztypeelf>, <modularmachinery:blockcasing:4>]]);
recipes.addShaped(<modulardiversity:blockmanainputhatch>, [[<modularmachinery:blockcasing:4>, <botania:quartztypeelf>, <modularmachinery:blockcasing:4>],[<botania:quartztypeelf>, <botania:manatablet>, <botania:quartztypeelf>], [<modularmachinery:blockcasing:4>, <botania:quartztypeelf>, <modularmachinery:blockcasing:4>]]);
recipes.addShaped(<modularmachinery:blockcasing:1>, [[<modularmachinery:itemmodularium>, <minecraft:iron_bars>, <modularmachinery:itemmodularium>],[<minecraft:iron_bars>, null, <minecraft:iron_bars>], [<modularmachinery:itemmodularium>, <minecraft:iron_bars>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing:3>, [[<modularmachinery:itemmodularium>, <ore:gearSteel>, <modularmachinery:itemmodularium>],[<ore:gearSteel>, null, <ore:gearSteel>], [<modularmachinery:itemmodularium>, <ore:gearSteel>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modularmachinery:blockcasing:5>, [[<modularmachinery:itemmodularium>, <ore:circuitBasic>, <modularmachinery:itemmodularium>],[<ore:circuitBasic>, null, <ore:circuitBasic>], [<modularmachinery:itemmodularium>, <ore:circuitBasic>, <modularmachinery:itemmodularium>]]);
recipes.addShaped(<modulardiversity:blockmeklaseracceptor>, [[<modularmachinery:blockcasing>, <ore:ingotRedAlloy>, <modularmachinery:blockcasing>],[<ore:ingotRedAlloy>, <mekanism:machineblock2:14>, <ore:ingotRedAlloy>], [<modularmachinery:blockcasing>, <ore:ingotRedAlloy>, <modularmachinery:blockcasing>]]);
recipes.addShaped(<mysticalagriculture:watering_can:4>, [[<ore:ingotSupremium>, <mysticalagriculture:crafting:54>, <mysticalagriculture:crafting:48>],[<ore:ingotSupremium>, <mysticalagriculture:watering_can:3>, <ore:ingotSupremium>], [null, <ore:ingotSupremium>, null]]);
recipes.addShaped(<mysticalagriculture:watering_can:3>, [[<ore:ingotSuperium>, <mysticalagriculture:crafting:53>, <mysticalagriculture:crafting:48>],[<ore:ingotSuperium>, <mysticalagriculture:watering_can:2>, <ore:ingotSuperium>], [null, <ore:ingotSuperium>, null]]);
recipes.addShaped(<mysticalagriculture:watering_can:2>, [[<ore:ingotIntermedium>, <mysticalagriculture:crafting:52>, <mysticalagriculture:crafting:48>],[<ore:ingotIntermedium>, <mysticalagriculture:watering_can:1>, <ore:ingotIntermedium>], [null, <ore:ingotIntermedium>, null]]);
recipes.addShaped(<mysticalagriculture:watering_can:1>, [[<ore:ingotPrudentium>, <mysticalagriculture:crafting:51>, <mysticalagriculture:crafting:48>],[<ore:ingotPrudentium>, <mysticalagriculture:watering_can>, <ore:ingotPrudentium>], [null, <ore:ingotPrudentium>, null]]);
recipes.addShaped(<tp:watering_can>, [[<ore:ingotTin>, <minecraft:dye:15>, null],[<ore:ingotTin>, <mysticalagriculture:watering_can>, <ore:ingotTin>], [null, <ore:ingotTin>, null]]);
recipes.addShapeless(<woot:layout>, [<xreliquary:mob_ingredient:3>,<xreliquary:mob_ingredient:1>,<minecraft:book>]);
recipes.addShaped(<woot:structure:5>, [[<woot:stygianironingot>, <erebus:materials:21>, <woot:stygianironingot>],[<erebus:materials:21>, <woot:factorybase>, <erebus:materials:21>], [<woot:stygianironingot>, <erebus:materials:21>, <woot:stygianironingot>]]);
recipes.addShaped(<woot:structure>, [[<woot:stygianironingot>, <xreliquary:mob_ingredient:6>, <woot:stygianironingot>],[<xreliquary:mob_ingredient:6>, <woot:factorybase>, <xreliquary:mob_ingredient:6>], [<woot:stygianironingot>, <xreliquary:mob_ingredient:6>, <woot:stygianironingot>]]);
recipes.addShaped(<woot:structure:1>, [[<woot:stygianironingot>, <xreliquary:mob_ingredient>, <woot:stygianironingot>],[<xreliquary:mob_ingredient>, <woot:factorybase>, <xreliquary:mob_ingredient>], [<woot:stygianironingot>, <xreliquary:mob_ingredient>, <woot:stygianironingot>]]);
recipes.addShaped(<tp:growth_upgrade_two>, [[<mysticalagriculture:growth_accelerator>, <minecraft:end_crystal>, <mysticalagriculture:growth_accelerator>],[<thermalfoundation:glass_alloy:7>, <tp:growth_upgrade>, <thermalfoundation:glass_alloy:7>], [<mysticalagriculture:growth_accelerator>, <minecraft:end_crystal>, <mysticalagriculture:growth_accelerator>]]);
recipes.addShaped(<tp:growth_upgrade>, [[<ore:ingotInvar>, <xreliquary:fertile_lilypad>, <ore:ingotInvar>],[<ore:blockGlass>, <tp:growth_block>, <ore:blockGlass>], [<ore:ingotInvar>, <xreliquary:fertile_lilypad>, <ore:ingotInvar>]]);
recipes.addShaped(<tp:growth_block>, [[<ore:ingotIron>, <minecraft:bone_block>, <ore:ingotIron>],[<lordcraft:util>, <minecraft:sea_lantern>, <lordcraft:util>], [<ore:ingotIron>, <minecraft:bone_block>, <ore:ingotIron>]]);
recipes.addShaped(<bloodmagic:soul_forge>, [[<ore:ingotIron>, null, <ore:ingotIron>],[<ore:stone>, <lordcraft:util:2>, <ore:stone>], [<ore:stone>, <ore:blockMetal>, <ore:stone>]]);
recipes.addShaped(<bloodmagic:soul_snare> * 4, [[<ore:ingotIron>, <ore:string>, <ore:ingotIron>],[<ore:string>, <lordcraft:dust_magic>, <ore:string>], [<ore:ingotIron>, <ore:string>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:diamond>, [[<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>],[<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>], [<ore:nuggetDiamond>, <ore:nuggetDiamond>, <ore:nuggetDiamond>]]);
recipes.addShaped(<armorplus:workbench>, [[<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>],[<ore:blockCharcoal>, <ore:workbench>, <ore:blockCharcoal>], [<ore:blockCharcoal>, null, <ore:blockCharcoal>]]);
recipes.addShaped(<armorplus:workbench>, [[<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>],[<ore:blockCoal>, <ore:workbench>, <ore:blockCoal>], [<ore:blockCoal>, null, <ore:blockCoal>]]);
recipes.addShaped(<magneticraft:crafting:6>, [[<ore:string>, <ore:string>, <ore:string>],[<ore:string>, null, <ore:string>], [<ore:string>, <ore:string>, <ore:string>]]);
recipes.addShaped(<astralsorcery:itemjournal>, [[null, <lordcraft:crystal_basic_lightning>, null],[<ore:gemAquamarine>, <minecraft:book>, <ore:gemAquamarine>], [null, <lordcraft:crystal_basic_lightning>, null]]);
recipes.addShaped(<abyssalcraft:necronomicon>, [[<lordcraft:crystal_basic_dark>, <lordcraft:crystal_basic_dark>, <ore:ingotIron>],[<minecraft:rotten_flesh>, <minecraft:book>, <lordcraft:crystal_basic_dark>], [<lordcraft:crystal_basic_dark>, <lordcraft:crystal_basic_dark>, <ore:ingotIron>]]);
recipes.addShaped(<abyssalcraft:shoggothbiomass>, [[<ore:gemCoralium>, <ore:gemCoralium>, <ore:gemCoralium>],[<ore:gemCoralium>, <ore:blockSlime>, <ore:gemCoralium>], [<ore:gemCoralium>, <ore:gemCoralium>, <ore:gemCoralium>]]);
recipes.addShaped(<magneticraft:water_generator>, [[<ore:plateTungsten>, <minecraft:water_bucket>, <ore:plateTungsten>],[<minecraft:water_bucket>, <nuclearcraft:water_source>, <minecraft:water_bucket>], [<ore:plateTungsten>, <minecraft:water_bucket>, <ore:plateTungsten>]]);
recipes.addShaped(<magneticraft:small_tank>, [[<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>],[<ore:blockGlass>, null, <ore:blockGlass>], [<ore:blockGlass>, <ore:plateCopper>, <ore:blockGlass>]]);
recipes.addShapeless(<magneticraft:crafting:5>, [<ore:plateIron>, <exnihilocreatio:item_mesh:3>]);
recipes.addShaped(<botania:altar>, [[<lordcraft:crystal_basic_nature>, <mysticalagriculture:crafting:10>, <lordcraft:crystal_basic_nature>],[null, <ore:stone>, null], [<ore:stone>, <ore:stone>, <ore:stone>]]);
recipes.addShapeless(<minecraft:flint_and_steel>, [<ore:ingotSteel>, <ore:flint>]);
recipes.addShaped(<minecraft:bucket>, [[null, null, null],[<ore:plateIron>, null, <ore:plateIron>], [null, <ore:plateIron>, null]]);
recipes.addShaped(<minecraft:bucket>, [[<ore:plateIron>, null, <ore:plateIron>],[null, <ore:plateIron>, null], [null, null, null]]);
recipes.addShapedMirrored(<solarflux:mirror> * 3, [[<ore:blockGlass>, <ore:blockGlass>, <ore:blockGlass>],[null, <ore:ingotIron>, null], [null, null, null]]);
recipes.addShapedMirrored(<extendedcrafting:crafting_table>, [[null, <ore:chest>, null],[null, <ore:workbench>, null], [null, null, null]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade:5>, [[<ore:nuggetElectrum>, <projectred-exploration:peridot_helmet>, <ore:nuggetElectrum>],[<projectred-exploration:sapphire_helmet>, <ore:alloyBasic>, <projectred-exploration:ruby_helmet>], [<ore:nuggetElectrum>, <ore:ingotGold>, <ore:nuggetElectrum>]]);

recipes.replaceAllOccurences(<tconstruct:ingots:0>, <ore:ingotCobalt>, <mysticalagriculture:cobalt_seeds>);
recipes.replaceAllOccurences(<tconstruct:ingots:1>, <ore:ingotArdite>, <mysticalagriculture:ardite_seeds>);
recipes.replaceAllOccurences(<randomthings:glowingmushroom>, <ore:ShroomGlowing>, <randomthings:ingredient:5>);
recipes.replaceAllOccurences(<extraplanets:tier5_items:7>, <ore:ingotNickel>, <extraplanets:advanced_fuel_loader>);
recipes.replaceAllOccurences(<extraplanets:tier11_items:7>, <ore:ingotPlatinum>, <extraplanets:advanced_launch_pad:3>);
recipes.replaceAllOccurences(<extraplanets:ingot_lead:0>, <ore:ingotLead>, <extraplanets:electric_parts:1>);
recipes.replaceAllOccurences(<galacticraftplanets:basic_item_venus>, <ore:ingotLead>, <extraplanets:electric_parts:1>);
recipes.replaceAllOccurences(<extraplanets:pluto:7>, <ore:blockTungsten>, <extraplanets:advanced_launch_pad:1>);
recipes.replaceAllOccurences(<extraplanets:tier8_items:5>, <ore:ingotZinc>, <extraplanets:advanced_launch_pad:1>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:decorative_blocks:13>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:advanced_oxygen_compressor:4>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:advanced_oxygen_compressor:0>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:saturn:7>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_sword>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_shovel>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_pickaxe>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_hoe>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_axe>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_legings>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_helmet>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_chest>);
recipes.replaceAllOccurences(<extraplanets:tier6_items:5>, <ore:ingotMagnesium>, <extraplanets:magnesium_boots>);
recipes.replaceAllOccurences(<projecte:item.pe_gem_density>, <lordcraft:crystal_basic_earthb>, <projecte:item.pe_void_ring>);
recipes.replaceAllOccurences(<projecte:item.pe_harvest_god>, <actuallyadditions:item_growth_ring>, <projecte:item.pe_arcana_ring>);
//File End
